BeSeenium: beseenium.controller.ActionDataFactory.ActionDataFactory Class Reference
beseenium.controller.ActionDataFactory.ActionDataFactory Class Reference
This Class conforms to a 'factory' pattern, it allows the creation of different ActionData instances.
Public Member Functions
ActionDataFactory () throws MalformedURLException
default constructor, initialises internal map and populates it
void setCapabilities (String key, String value) throws MalformedURLException
when you wish to use the remote webdriver, then the capabilities must be set first, this method provides a convenient way to set them.
ActionData makeActionData ()
provides an ActionData devoid of any pre initialised data, i.e.
ActionData makeActionData (String ActionDataKey) throws ActionDataFactoryException
make a specific actionData containing a specific WebDriver.
Private Member Functions
void mapEntries ()
populate the map with 'MakeActionData' derived types
Private Attributes
Map< String, MakeData > ActionDataMap
container for string value pairs associated with this factory
DesiredCapabilities capabilities
this is used by the RemoteWebDriver to create an appropriate browser simulation
URL URL
needed by the RemoteWebDriver, holds the location of the server to run simulations on
ActionData emptyActionData
Detailed Description
This Class conforms to a 'factory' pattern, it allows the creation of different ActionData instances.
Author
JPC Hanson
Definition at line 34 of file ActionDataFactory.java.
Constructor & Destructor Documentation
beseenium.controller.ActionDataFactory.ActionDataFactory.ActionDataFactory () throws MalformedURLException
default constructor, initialises internal map and populates it
Exceptions
MalformedURLException
Definition at line 49 of file ActionDataFactory.java.
References beseenium.controller.ActionDataFactory.ActionDataFactory.mapEntries().
Member Function Documentation
ActionData beseenium.controller.ActionDataFactory.ActionDataFactory.makeActionData ()
provides an ActionData devoid of any pre initialised data, i.e.
completely empty. mostly used by ActionFactory.
Returns
ActionData that is completely empty.
Implements beseenium.controller.ActionDataFactory.MakeData.
Definition at line 91 of file ActionDataFactory.java.
References beseenium.controller.ActionDataFactory.ActionDataFactory.emptyActionData.
Referenced by beseenium.controller.Test.setBrowser().
ActionData beseenium.controller.ActionDataFactory.ActionDataFactory.makeActionData (String ActionDataKey) throws ActionDataFactoryException
make a specific actionData containing a specific WebDriver.
Parameters
ActionDataKey the type of ActionData you wish to specify.
Returns
ActionData appropriate to the ActionDataKey passed in
Exceptions
ActionDataFactoryException if ActionDataKey does not correspond to a known ActionData implementation.
Definition at line 103 of file ActionDataFactory.java.
void beseenium.controller.ActionDataFactory.ActionDataFactory.mapEntries () private
populate the map with 'MakeActionData' derived types
Definition at line 126 of file ActionDataFactory.java.
Referenced by beseenium.controller.ActionDataFactory.ActionDataFactory.ActionDataFactory().
void beseenium.controller.ActionDataFactory.ActionDataFactory.setCapabilities (String key, String value) throws MalformedURLException
when you wish to use the remote webdriver, then the capabilities must be set first, this method provides a convenient way to set them.
Parameters
key the capability you wish to set
value the value you wish to set it to.
Exceptions
MalformedURLException
Definition at line 67 of file ActionDataFactory.java.
References beseenium.controller.ActionDataFactory.ActionDataFactory.URL.
Referenced by beseenium.controller.Test.configureRemoteDriver().
Member Data Documentation
Map<String, MakeData> beseenium.controller.ActionDataFactory.ActionDataFactory.ActionDataMap private
container for string value pairs associated with this factory
Definition at line 37 of file ActionDataFactory.java.
DesiredCapabilities beseenium.controller.ActionDataFactory.ActionDataFactory.capabilities private
this is used by the RemoteWebDriver to create an appropriate browser simulation
Definition at line 39 of file ActionDataFactory.java.
ActionData beseenium.controller.ActionDataFactory.ActionDataFactory.emptyActionData private
Definition at line 43 of file ActionDataFactory.java.
Referenced by beseenium.controller.ActionDataFactory.ActionDataFactory.makeActionData().
URL beseenium.controller.ActionDataFactory.ActionDataFactory.URL private
needed by the RemoteWebDriver, holds the location of the server to run simulations on
Definition at line 41 of file ActionDataFactory.java.
Referenced by beseenium.controller.ActionDataFactory.ActionDataFactory.setCapabilities().
The documentation for this class was generated from the following file:
ActionDataFactory.java