BeSeenium: beseenium.controller.ActionFactory.ActionFactory Class Reference
beseenium.controller.ActionFactory.ActionFactory Class Reference
this class is a factory for creating actions, it uses a factory method style pattern and a map implementation.
Public Member Functions
ActionFactory (ActionDataFactory actionDataFactory) throws ActionDataFactoryException, MalformedURLException
default constructor creates and populates internal map
AbstractAction makeAction (String actionKey) throws ActionFactoryException
creates an Action
Private Member Functions
void populateActionMap () throws ActionDataFactoryException
creates all possible actions and populates the map with them.
Private Attributes
Map< String, MakeAction > actionMap
the map to store the actions in
ActionDataFactory actionDataFactory
internal ActionDataFactory reference
Detailed Description
this class is a factory for creating actions, it uses a factory method style pattern and a map implementation.
Author
JPC Hanson
Definition at line 62 of file ActionFactory.java.
Constructor & Destructor Documentation
beseenium.controller.ActionFactory.ActionFactory.ActionFactory (ActionDataFactory actionDataFactory) throws ActionDataFactoryException, MalformedURLException
default constructor creates and populates internal map
Parameters
actionDataFactory
Exceptions
ActionDataFactoryException
MalformedURLException
Definition at line 76 of file ActionFactory.java.
References beseenium.controller.ActionFactory.ActionFactory.actionDataFactory, and beseenium.controller.ActionFactory.ActionFactory.populateActionMap().
Member Function Documentation
AbstractAction beseenium.controller.ActionFactory.ActionFactory.makeAction (String actionKey) throws ActionFactoryException
creates an Action
Returns
AbstractAction
Exceptions
ActionFactoryException
ActionDataFactoryException
Definition at line 91 of file ActionFactory.java.
Referenced by beseenium.controller.Test.addAction(), and beseenium.controller.Test.emergencyShutdown().
void beseenium.controller.ActionFactory.ActionFactory.populateActionMap () throws ActionDataFactoryException private
creates all possible actions and populates the map with them.
Exceptions
ActionDataFactoryException
Definition at line 105 of file ActionFactory.java.
Referenced by beseenium.controller.ActionFactory.ActionFactory.ActionFactory().
Member Data Documentation
ActionDataFactory beseenium.controller.ActionFactory.ActionFactory.actionDataFactory private
internal ActionDataFactory reference
Definition at line 67 of file ActionFactory.java.
Referenced by beseenium.controller.ActionFactory.ActionFactory.ActionFactory().
Map<String, MakeAction> beseenium.controller.ActionFactory.ActionFactory.actionMap private
the map to store the actions in
Definition at line 65 of file ActionFactory.java.
The documentation for this class was generated from the following file:
ActionFactory.java