BeSeenium: beseenium.view.outputHandlers.formatters.AbstractOutputFormatter Interface Reference
beseenium.view.outputHandlers.formatters.AbstractOutputFormatter Interface Reference
Interface that all output formatter classes should subscribe to, allowing the servlet to request an appropriate output format specific to a users request.
Public Member Functions
String asKeyVal (String key, String val, String delimiter)
format the given string as a key value pair specific to the derived type.
String asKVset (String label, String stringToFormat, String delimiter)
format the given string as a key value set specific to the derived type.
String asKVsuperSet (String label, String stringToFormat, String delimiter)
format the given string as a key value super set specific to the derived type.
String finalForm (String label, String stringToFormat, String delimiter)
do some final formatting on the given string to put it in the final form specific to the derived type.
Detailed Description
Interface that all output formatter classes should subscribe to, allowing the servlet to request an appropriate output format specific to a users request.
Output formatting is divided into 4 generic sections which should be able to apply to all formats that the user could request:
KeyVal a key value pair, in the case of JSON this would be "key":"value" for XML it would be <key>value</key> and so on.
KVset this is a set of key value pairs organised in a way that makes sense to the output type: JSON: {"key1":"val1", "key2":"val2", etc} XML:<setName><key1>value1</key1><key2>value2 </key2></setName> and so on.
KVsuperSet this is a set of key value sets organised in a way that makes sense to the output type
Author
Jan P.C. Hanson
Definition at line 39 of file AbstractOutputFormatter.java.
Member Function Documentation
String beseenium.view.outputHandlers.formatters.AbstractOutputFormatter.asKeyVal (String key, String val, String delimiter)
format the given string as a key value pair specific to the derived type.
Parameters
key the key
val the value
delimiter a string to use as a delimiter
Returns
String formatted as requested
Implemented in beseenium.view.outputHandlers.formatters.JsonFormatter, and beseenium.view.outputHandlers.formatters.BasicFormatter.
Referenced by beseenium.view.outputHandlers.compositors.AddActionCompositor.format(), beseenium.view.outputHandlers.compositors.ExecuteCompositor.format(), and beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.format().
String beseenium.view.outputHandlers.formatters.AbstractOutputFormatter.asKVset (String label, String stringToFormat, String delimiter)
format the given string as a key value set specific to the derived type.
Parameters
stringToFormat the string to format
label a string to use as a label in the KVSet (optional)
delimiter a string to use as a delimiter
Returns
String formatted as requested
Implemented in beseenium.view.outputHandlers.formatters.JsonFormatter, and beseenium.view.outputHandlers.formatters.BasicFormatter.
Referenced by beseenium.view.outputHandlers.compositors.AddActionCompositor.format(), beseenium.view.outputHandlers.compositors.ExecuteCompositor.format(), and beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.format().
String beseenium.view.outputHandlers.formatters.AbstractOutputFormatter.asKVsuperSet (String label, String stringToFormat, String delimiter)
format the given string as a key value super set specific to the derived type.
Parameters
stringToFormat the string to format
label a string to use as a label in the KVsuperSet (optional)
delimiter a string to use as a delimiter
Returns
String formatted as requested
Implemented in beseenium.view.outputHandlers.formatters.BasicFormatter, and beseenium.view.outputHandlers.formatters.JsonFormatter.
Referenced by beseenium.view.outputHandlers.compositors.AddActionCompositor.finalFormat(), beseenium.view.outputHandlers.compositors.ExecuteCompositor.finalFormat(), and beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.finalFormat().
String beseenium.view.outputHandlers.formatters.AbstractOutputFormatter.finalForm (String label, String stringToFormat, String delimiter)
do some final formatting on the given string to put it in the final form specific to the derived type.
Parameters
stringToFormat the string to format
label a string to use as a label in the final form (optional)
delimiter a string to use as a delimiter
Returns
String formatted as requested
Implemented in beseenium.view.outputHandlers.formatters.BasicFormatter, and beseenium.view.outputHandlers.formatters.JsonFormatter.
Referenced by beseenium.view.outputHandlers.compositors.AddActionCompositor.finalFormat(), beseenium.view.outputHandlers.compositors.ExecuteCompositor.finalFormat(), and beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.finalFormat().
The documentation for this interface was generated from the following file:
AbstractOutputFormatter.java