BeSeenium: beseenium.view.BeSeeniumServlet.doGet
void beseenium.view.BeSeeniumServlet.doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
Logger.
The method that actually does all the work.
Parameters
request a http request
response the http response
Exceptions
ServletException
IOException
Definition at line 58 of file BeSeeniumServlet.java.
References beseenium.view.inputHandlers.InputHandler.handleInput(), beseenium.view.outputHandlers.OutputHandler.handleRequests(), and beseenium.view.outputHandlers.OutputHandler.setRequests().