BeSeenium: beseenium.model.helpers.FormatOutput Class Reference
beseenium.model.helpers.FormatOutput Class Reference
This helper class provides methods to format the output of individual actions.
Static Public Member Functions
static String formatFindElementOutput (List< WebElement > elements, int n)
formats the output string of a findElementBy...
Detailed Description
This helper class provides methods to format the output of individual actions.
Author
Jan P.C. Hanson
Definition at line 26 of file FormatOutput.java.
Member Function Documentation
static String beseenium.model.helpers.FormatOutput.formatFindElementOutput (List< WebElement > elements, int n) static
formats the output string of a findElementBy...
output string
Parameters
elements a List<WebElement> containing all elements to be formatted
n an integer value determining which element to act on, if n = -1 then all elements in the list will be formatted.
Returns
String containing the formatted output.
Definition at line 35 of file FormatOutput.java.
Referenced by beseenium.model.action.findElementsBy.FindElementsByClass.execute(), beseenium.model.action.findElementsBy.FindElementsByCss.execute(), beseenium.model.action.findElementsBy.FindElementsByName.execute(), beseenium.model.action.findElementsBy.FindElementsById.execute(), beseenium.model.action.findElementsBy.FindElementsByXpath.execute(), beseenium.model.action.findElementsBy.FindElementsByLinkTxt.execute(), beseenium.model.action.findElementsBy.FindElementsByTagName.execute(), and beseenium.model.action.findElementsBy.FindElementsByPartialLinkTxt.execute().
The documentation for this class was generated from the following file:
FormatOutput.java