BeSeenium: beseenium.view.outputHandlers.compositors.CapabilitiesCompositor Class Reference
beseenium.view.outputHandlers.compositors.CapabilitiesCompositor Class Reference
Copyright(C) 2015 Jan P.C.
Public Member Functions
CapabilitiesCompositor (AbstractOutputFormatter format)
specifies the format that the user wishes the output returned in e.g.
String composite (String compositorString, String stringToComposite)
This method provides functionality to composite the string into the format specified by the user on creation of this object.
Private Member Functions
String format (int actionNo, String[][] results, String delimiter)
does the formatting of the keyVal and KVset
String finalFormat (String formattedResults, String label)
does the final formatting of the JSON object
Additional Inherited Members
Protected Member Functions inherited from beseenium.view.outputHandlers.compositors.AbstractCompositor
AbstractCompositor (AbstractOutputFormatter format)
default constructor, sets the formatter.
Protected Attributes inherited from beseenium.view.outputHandlers.compositors.AbstractCompositor
AbstractOutputFormatter formatter
reference to the formatter used e.g.
Detailed Description
Copyright(C) 2015 Jan P.C.
Hanson & BeSeen Marketing Ltd
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jan P.C. Hanson
Definition at line 26 of file CapabilitiesCompositor.java.
Constructor & Destructor Documentation
beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.CapabilitiesCompositor (AbstractOutputFormatter format)
specifies the format that the user wishes the output returned in e.g.
JSON, XML, etc
Parameters
format the format that the user wishes the output returned in e.g. JSON, XML, etc
Definition at line 33 of file CapabilitiesCompositor.java.
Member Function Documentation
String beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.composite (String compositorString, String stringToComposite)
This method provides functionality to composite the string into the format specified by the user on creation of this object.
Parameters
compositorString representation of the type of string that this is i.e. execute, addAction, capabilities or browser.
stringToComposite the string that requires formatting
Returns
String the formatted string.
Definition at line 47 of file CapabilitiesCompositor.java.
References beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.finalFormat(), beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.format(), and beseenium.view.helpers.StringSplit.generic2d().
String beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.finalFormat (String formattedResults, String label) private
does the final formatting of the JSON object
Parameters
results the previously formatted results
Returns
fully formatted JSON
Definition at line 87 of file CapabilitiesCompositor.java.
References beseenium.view.outputHandlers.formatters.AbstractOutputFormatter.asKVsuperSet(), beseenium.view.outputHandlers.formatters.AbstractOutputFormatter.finalForm(), and beseenium.view.outputHandlers.compositors.AbstractCompositor.formatter.
Referenced by beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.composite().
String beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.format (int actionNo, String results[][], String delimiter) private
does the formatting of the keyVal and KVset
Parameters
actionNo the number of the action to use as a key in the KeyVal
result the result to use as the value of a KeyVal
delimiter string delimiter to add to the end of each KVset
Returns
String of the form {"action":"actionNo", "result":"result value"}
Definition at line 74 of file CapabilitiesCompositor.java.
References beseenium.view.outputHandlers.formatters.AbstractOutputFormatter.asKeyVal(), beseenium.view.outputHandlers.formatters.AbstractOutputFormatter.asKVset(), and beseenium.view.outputHandlers.compositors.AbstractCompositor.formatter.
Referenced by beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.composite().
The documentation for this class was generated from the following file:
CapabilitiesCompositor.java