BeSeenium: beseenium.view.outputHandlers.compositors.AddActionCompositor Class Reference
beseenium.view.outputHandlers.compositors.AddActionCompositor Class Reference
Public Member Functions
String composite (String compositorString, String stringToComposite)
This method provides functionality to composite the string into the format specified by the user on creation of this object.
Protected Member Functions
AddActionCompositor (AbstractOutputFormatter format)
Protected Member Functions inherited from beseenium.view.outputHandlers.compositors.AbstractCompositor
AbstractCompositor (AbstractOutputFormatter format)
default constructor, sets the formatter.
Private Member Functions
String format (int actionNo, String[][] results, String delimiter)
does the formatting of the keyVal and KVset
String finalFormat (String formattedResults)
does the final formatting of the JSON object
boolean containsError (String msg)
check if result string contains "!!ERROR!!"
Additional Inherited Members
Protected Attributes inherited from beseenium.view.outputHandlers.compositors.AbstractCompositor
AbstractOutputFormatter formatter
reference to the formatter used e.g.
Detailed Description
Author
Jan P.C. Hanson
Definition at line 13 of file AddActionCompositor.java.
Constructor & Destructor Documentation
beseenium.view.outputHandlers.compositors.AddActionCompositor.AddActionCompositor (AbstractOutputFormatter format) protected
Parameters
format
Definition at line 19 of file AddActionCompositor.java.
Member Function Documentation
String beseenium.view.outputHandlers.compositors.AddActionCompositor.composite (String compositorString, String stringToComposite)
This method provides functionality to composite the string into the format specified by the user on creation of this object.
Parameters
compositorString representation of the type of string that this is i.e. execute, addAction, capabilities or browser.
stringToComposite the string that requires formatting
Returns
String the formatted string.
Definition at line 31 of file AddActionCompositor.java.
References beseenium.view.outputHandlers.compositors.AddActionCompositor.containsError(), beseenium.view.outputHandlers.compositors.AddActionCompositor.finalFormat(), beseenium.view.outputHandlers.compositors.AddActionCompositor.format(), and beseenium.view.helpers.StringSplit.generic2d().
boolean beseenium.view.outputHandlers.compositors.AddActionCompositor.containsError (String msg) private
check if result string contains "!!ERROR!!"
Parameters
msg String to check
Returns
true if contains, false otherwise.
Definition at line 89 of file AddActionCompositor.java.
Referenced by beseenium.view.outputHandlers.compositors.AddActionCompositor.composite().
String beseenium.view.outputHandlers.compositors.AddActionCompositor.finalFormat (String formattedResults) private
does the final formatting of the JSON object
Parameters
results the previously formatted results
Returns
fully formatted JSON
Definition at line 76 of file AddActionCompositor.java.
References beseenium.view.outputHandlers.formatters.AbstractOutputFormatter.asKVsuperSet(), beseenium.view.outputHandlers.formatters.AbstractOutputFormatter.finalForm(), and beseenium.view.outputHandlers.compositors.AbstractCompositor.formatter.
Referenced by beseenium.view.outputHandlers.compositors.AddActionCompositor.composite().
String beseenium.view.outputHandlers.compositors.AddActionCompositor.format (int actionNo, String results[][], String delimiter) private
does the formatting of the keyVal and KVset
Parameters
actionNo the number of the action to use as a key in the KeyVal
result the result to use as the value of a KeyVal
delimiter string delimiter to add to the end of each KVset
Returns
String of the form {"action":"actionNo", "result":"result value"}
Definition at line 61 of file AddActionCompositor.java.
References beseenium.view.outputHandlers.formatters.AbstractOutputFormatter.asKeyVal(), beseenium.view.outputHandlers.formatters.AbstractOutputFormatter.asKVset(), and beseenium.view.outputHandlers.compositors.AbstractCompositor.formatter.
Referenced by beseenium.view.outputHandlers.compositors.AddActionCompositor.composite().
The documentation for this class was generated from the following file:
AddActionCompositor.java