BeSeenium: beseenium.view.BeSeeniumServlet Class Reference
beseenium.view.BeSeeniumServlet Class Reference
BeSeeniumServlet is a servlet that provide functionality that grabs the query strings from a http request and passes it on to the URLHandler, which gives back a result string which this servlet then inserts into the http response.
Protected Member Functions
void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
Logger.
Static Private Attributes
static final long serialVersionUID = -2842549406742289709L
need this to avoid warnings
Detailed Description
BeSeeniumServlet is a servlet that provide functionality that grabs the query strings from a http request and passes it on to the URLHandler, which gives back a result string which this servlet then inserts into the http response.
Author
Jan P.C. Hanson
Definition at line 42 of file BeSeeniumServlet.java.
Member Function Documentation
void beseenium.view.BeSeeniumServlet.doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
Logger.
The method that actually does all the work.
Parameters
request a http request
response the http response
Exceptions
ServletException
IOException
Definition at line 58 of file BeSeeniumServlet.java.
References beseenium.view.inputHandlers.InputHandler.handleInput(), beseenium.view.outputHandlers.OutputHandler.handleRequests(), and beseenium.view.outputHandlers.OutputHandler.setRequests().
Member Data Documentation
final long beseenium.view.BeSeeniumServlet.serialVersionUID = -2842549406742289709L static private
need this to avoid warnings
Definition at line 45 of file BeSeeniumServlet.java.
The documentation for this class was generated from the following file:
BeSeeniumServlet.java