BeSeenium: beseenium.view.inputHandlers.InputHandler.handleInput
Map<String, AbstractTestRequest> beseenium.view.inputHandlers.InputHandler.handleInput (String caps, String brwsr, String actns)
Generates a map of string descriptors to requests from the given parameters, ending with a request to execute the test.
keys are "capabilities", "browser", "actions", "execute"
Parameters
caps the capabilities passed in as a string.
brwsr the browser passed in as a string.
actns the actions to add passed in as a string.
Returns
Map<String, AbstractTestRequest> addressable by the strings: capabilities, browser, actions & execute.
Definition at line 59 of file InputHandler.java.
References beseenium.view.inputHandlers.InputHandler.handleAddActions(), beseenium.view.inputHandlers.InputHandler.handleBrowser(), beseenium.view.inputHandlers.InputHandler.handleCapabilities(), beseenium.view.inputHandlers.InputHandler.handleExecuteRequest(), and beseenium.view.inputHandlers.InputHandler.testRequests.
Referenced by beseenium.view.BeSeeniumServlet.doGet().