BeSeenium: beseenium.model.ActionInvoker.execute
List<String> beseenium.model.ActionInvoker.execute () throws ActionDataException, ActionException
iterates through the commands stored in the list and executes
Returns
List<String> the results of the various actions, to be used in reporting.
Exceptions
ActionException
ActionDataException
Definition at line 87 of file ActionInvoker.java.
References beseenium.model.action.AbstractAction.execute(), beseenium.model.action.AbstractAction.getActionData(), beseenium.model.actionData.ActionData.setDriver(), and beseenium.model.actionData.ActionData.setInputParam().
Referenced by beseenium.controller.Test.emergencyShutdown(), and beseenium.controller.Test.executeActions().