BeSeenium: beseenium.view.inputHandlers.requests.AbstractTestRequest Class Reference
beseenium.view.inputHandlers.requests.AbstractTestRequest Class Reference abstract
This class is the abstract base class for a series of request objects relating to various parts of a test's functionality, e.g.
Public Member Functions
abstract String executeRequest (Test test) throws Exception
Contains the implementation of the request.
Protected Member Functions
AbstractTestRequest (String requestData)
Constructor, instantiates the object with the data provided by the URL parameter.
Protected Attributes
String requestData
the data passed in from the URL parameter
Detailed Description
This class is the abstract base class for a series of request objects relating to various parts of a test's functionality, e.g.
capabilities, browser, addActions etc.
Author
Jan P.C. Hanson
Definition at line 25 of file AbstractTestRequest.java.
Constructor & Destructor Documentation
beseenium.view.inputHandlers.requests.AbstractTestRequest.AbstractTestRequest (String requestData) protected
Constructor, instantiates the object with the data provided by the URL parameter.
Parameters
requestData the data provided by the URL parameter.
Definition at line 34 of file AbstractTestRequest.java.
References beseenium.view.inputHandlers.requests.AbstractTestRequest.requestData.
Member Function Documentation
abstract String beseenium.view.inputHandlers.requests.AbstractTestRequest.executeRequest (Test test) throws Exception abstract
Contains the implementation of the request.
Returns
String representing the result of this request.
Referenced by beseenium.view.outputHandlers.requestHandlers.browserHandlers.RootBrowserHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.ActionNumberFormatHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.RootAddActionsHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.NoActionParamHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.executeHandlers.RootExecuteHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.browserHandlers.NoBrowserParamHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.executeHandlers.ActionDataExceptionHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.CapsActionDataHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.BadlyFormedCapsStringHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.browserHandlers.BrowserActionDataHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.BadlyFormattedActionHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.browserHandlers.WrongBrowserParamHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.RootCapabilitiesHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.AddActionDataHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.NonExistantActionHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.executeHandlers.ActionExceptionHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.EmptyCapsParamHandler.handleRequest(), and beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.MalformedURLHandler.handleRequest().
Member Data Documentation
String beseenium.view.inputHandlers.requests.AbstractTestRequest.requestData protected
the data passed in from the URL parameter
Definition at line 28 of file AbstractTestRequest.java.
Referenced by beseenium.view.inputHandlers.requests.AbstractTestRequest.AbstractTestRequest().
The documentation for this class was generated from the following file:
AbstractTestRequest.java