BeSeenium: beseenium.view.inputHandlers.requests.AbstractTestRequest.executeRequest
abstract String beseenium.view.inputHandlers.requests.AbstractTestRequest.executeRequest (Test test) throws Exception abstract
Contains the implementation of the request.
Returns
String representing the result of this request.
Referenced by beseenium.view.outputHandlers.requestHandlers.browserHandlers.RootBrowserHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.ActionNumberFormatHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.RootAddActionsHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.NoActionParamHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.executeHandlers.RootExecuteHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.browserHandlers.NoBrowserParamHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.executeHandlers.ActionDataExceptionHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.CapsActionDataHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.BadlyFormedCapsStringHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.browserHandlers.BrowserActionDataHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.BadlyFormattedActionHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.browserHandlers.WrongBrowserParamHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.AddActionDataHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.NonExistantActionHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.RootCapabilitiesHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.executeHandlers.ActionExceptionHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.EmptyCapsParamHandler.handleRequest(), and beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.MalformedURLHandler.handleRequest().