BeSeenium: beseenium.view.URLHandler Class Reference
beseenium.view.URLHandler Class Reference
The sole responsibility of this class is to translate parameters representing URL query strings from an http request into 'Test' functionality.
Public Member Functions
URLHandler () throws ActionDataFactoryException, MalformedURLException
default constructor, initialise a test to operate on
String handleURL (String capabilities, String browser, String addActions)
takes the URL parameters passed to it from the BeSeeniumServlet and uses it to populate and run a Test
Private Member Functions
String handleCapabilities (String capabilities)
takes an input from servlet(via handleURL method) in the form of string 'get' URL parameter 'capabilities' uses it to set the remoteDriver configuration, this is only of use when the browser type is set as 'remote'
String handleBrowser (String browser)
takes an input from servlet(via handleURL method) in the form of string 'get' URL parameter 'browser' ancd uses it to set the Test's WebDriver.
String handleAddActions (String addActions)
takes an input from servlet(via handleURL method) in the form of string 'get' URL parameter 'addActions' and uses it to add actions to the test.
String[][] splitString (String string)
split a string of the form "V01:V02:...:V0n|V11:V12:...:V1n|Vm1:Vm2:...:Vmn" into a 2d String array of the form {{V01,V02...V0n},{V11,V12...V1n}...{Vm1, Vm2...
String shutdown (Exception e)
in case something goes wrong the test should be able to shut down the current browser instance, or else there could potentially be many, for all intents and purposes, orphan processes floating about eating up memory....remember: always kill the orphans.
Static Private Attributes
static final Logger logger = LogManager.getLogger("BeSeenium.URLHandler")
Detailed Description
The sole responsibility of this class is to translate parameters representing URL query strings from an http request into 'Test' functionality.
Author
Jan P.C. Hanson
Definition at line 36 of file URLHandler.java.
Constructor & Destructor Documentation
beseenium.view.URLHandler.URLHandler () throws ActionDataFactoryException, MalformedURLException
default constructor, initialise a test to operate on
Exceptions
ActionDataFactoryException
MalformedURLException
Definition at line 50 of file URLHandler.java.
Member Function Documentation
String beseenium.view.URLHandler.handleAddActions (String addActions) private
takes an input from servlet(via handleURL method) in the form of string 'get' URL parameter 'addActions' and uses it to add actions to the test.
Parameters
addActions String of the form: "name+inputParam+optional|name+inputParam+optional|name+inputParam+optional|..."
Returns
String of the form: "ACTIONS ADDED:"+"[[action1, inputParam1, index1],[action2, inputParam2, index2]...[actionN, inputParamN, indexN]]
Definition at line 159 of file URLHandler.java.
References beseenium.controller.Test.addAction(), beseenium.view.URLHandler.shutdown(), and beseenium.view.URLHandler.splitString().
Referenced by beseenium.view.URLHandler.handleURL().
String beseenium.view.URLHandler.handleBrowser (String browser) private
takes an input from servlet(via handleURL method) in the form of string 'get' URL parameter 'browser' ancd uses it to set the Test's WebDriver.
Parameters
browser String representation of the WebDriver to use ("firefox"/"noWindows"/"remote"...etc)
Returns
String of the form: "BROWSER SET AS" + "<name of browser>" + newline
Definition at line 135 of file URLHandler.java.
References beseenium.controller.Test.setBrowser(), and beseenium.view.URLHandler.shutdown().
Referenced by beseenium.view.URLHandler.handleURL().
String beseenium.view.URLHandler.handleCapabilities (String capabilities) private
takes an input from servlet(via handleURL method) in the form of string 'get' URL parameter 'capabilities' uses it to set the remoteDriver configuration, this is only of use when the browser type is set as 'remote'
Parameters
capabilities String of the form "key+value|key+value|key+value|..."
Returns
String of the form "DESIRED CAPABILITES:" + "[[key1, value1], [key2, value2], [key3, value3]]" will return an error message if the input string is badly formatted
Definition at line 100 of file URLHandler.java.
References beseenium.controller.Test.configureRemoteDriver(), beseenium.view.URLHandler.shutdown(), and beseenium.view.URLHandler.splitString().
Referenced by beseenium.view.URLHandler.handleURL().
String beseenium.view.URLHandler.handleURL (String capabilities, String browser, String addActions)
takes the URL parameters passed to it from the BeSeeniumServlet and uses it to populate and run a Test
Parameters
capabilities String of the form "key+value|key+value|key+value|..."
browser String representation of the 'browser' query string can take the values: firefox, noWindows or remote(more to be added).
addActions String of the form: "name+inputParam+index|name+inputParam+index|name+inputParam+index|..."
Returns
String representation of the aggregate results of the individual actions. will return an error message with appropriate content if an exception is caught
Todo:
add more browser drivers
Definition at line 67 of file URLHandler.java.
References beseenium.controller.Test.executeActions(), beseenium.view.URLHandler.handleAddActions(), beseenium.view.URLHandler.handleBrowser(), beseenium.view.URLHandler.handleCapabilities(), and beseenium.view.URLHandler.shutdown().
String beseenium.view.URLHandler.shutdown (Exception e) private
in case something goes wrong the test should be able to shut down the current browser instance, or else there could potentially be many, for all intents and purposes, orphan processes floating about eating up memory....remember: always kill the orphans.
Parameters
e
Returns
verification string
Definition at line 210 of file URLHandler.java.
References beseenium.controller.Test.emergencyShutdown().
Referenced by beseenium.view.URLHandler.handleAddActions(), beseenium.view.URLHandler.handleBrowser(), beseenium.view.URLHandler.handleCapabilities(), and beseenium.view.URLHandler.handleURL().
String [][] beseenium.view.URLHandler.splitString (String string) private
split a string of the form "V01:V02:...:V0n|V11:V12:...:V1n|Vm1:Vm2:...:Vmn" into a 2d String array of the form {{V01,V02...V0n},{V11,V12...V1n}...{Vm1, Vm2...
Vmn}}
Parameters
string of the form "V01:V02:...:V0n|V11:V12:...:V1n|Vm1:Vm2:...:Vmn"
Returns
String[][] of the form {{V01,V02...V0n},{V11,V12...V1n}...{Vm1, Vm2... Vmn}}
Definition at line 189 of file URLHandler.java.
Referenced by beseenium.view.URLHandler.handleAddActions(), and beseenium.view.URLHandler.handleCapabilities().
Member Data Documentation
final Logger beseenium.view.URLHandler.logger = LogManager.getLogger("BeSeenium.URLHandler") static private
Definition at line 43 of file URLHandler.java.
The documentation for this class was generated from the following file:
URLHandler.java