BeSeenium: beseenium.view.URLHandler.handleBrowser
String beseenium.view.URLHandler.handleBrowser (String browser) private
takes an input from servlet(via handleURL method) in the form of string 'get' URL parameter 'browser' ancd uses it to set the Test's WebDriver.
Parameters
browser String representation of the WebDriver to use ("firefox"/"noWindows"/"remote"...etc)
Returns
String of the form: "BROWSER SET AS" + "<name of browser>" + newline
Definition at line 135 of file URLHandler.java.
References beseenium.controller.Test.setBrowser(), and beseenium.view.URLHandler.shutdown().
Referenced by beseenium.view.URLHandler.handleURL().