BeSeenium: beseenium.controller.Test Class Reference
beseenium.controller.Test Class Reference
blueprint for creating Test objects, a Test is ostensibly a series of actions that are performed one after the other.
Public Member Functions
Test () throws ActionDataFactoryException, MalformedURLException
constructs the Test object
void setBrowser (String browserDriver) throws ActionDataException
Set the browser that you want this test to run on.
void configureRemoteDriver (String key, String value) throws MalformedURLException
When using a 'remote' Driver set a capability of the driver i.e.
void addAction (String actionName, String inputParameter, int optionalIndex) throws ActionFactoryException
Add an action to this test.
void removeAction (int actionToRemove)
remove an action from this test.
List< String > executeActions () throws ActionDataException, ActionException
executes all actions in this test, in the sequence they were added
void emergencyShutdown () throws ActionDataException, ActionException
remove all actions from this test and close the browser instance associated with it.
Private Attributes
ActionFactory actionFactory
reference to internal ActionFactory
ActionDataFactory actionDataFactory
reference to internal ActionDataFactory
ActionInvoker invoker
reference to Action Invoker.
Detailed Description
blueprint for creating Test objects, a Test is ostensibly a series of actions that are performed one after the other.
provides methods for adding/removing actions configuring remote capabilities and other functionality that relates to creating and using a test.
this class acts as the client of command pattern governing the storage and execution of Abstract Actions.
Author
Jan P.C. Hanson
Definition at line 39 of file Test.java.
Constructor & Destructor Documentation
beseenium.controller.Test.Test () throws ActionDataFactoryException, MalformedURLException
constructs the Test object
Exceptions
ActionDataFactoryException
MalformedURLException
Definition at line 53 of file Test.java.
Member Function Documentation
void beseenium.controller.Test.addAction (String actionName, String inputParameter, int optionalIndex) throws ActionFactoryException
Add an action to this test.
Parameters
actionName the name of the Action to add
inputParameter the input parameter (if applicable) of the action to add
optionalIndex an optional index (if applicable) to specify the element that this action will be performed on(assuming one of the previous actions was a FindElement action)
Exceptions
ActionFactoryException
Definition at line 98 of file Test.java.
References beseenium.model.ActionInvoker.add(), and beseenium.controller.ActionFactory.ActionFactory.makeAction().
Referenced by beseenium.view.URLHandler.handleAddActions().
void beseenium.controller.Test.configureRemoteDriver (String key, String value) throws MalformedURLException
When using a 'remote' Driver set a capability of the driver i.e.
key='os' value='windows'
Parameters
key
value
Exceptions
MalformedURLException
Definition at line 84 of file Test.java.
References beseenium.controller.ActionDataFactory.ActionDataFactory.setCapabilities().
Referenced by beseenium.view.URLHandler.handleCapabilities().
void beseenium.controller.Test.emergencyShutdown () throws ActionDataException, ActionException
remove all actions from this test and close the browser instance associated with it.
Exceptions
ActionDataException
ActionException
Definition at line 129 of file Test.java.
References beseenium.model.ActionInvoker.add(), beseenium.model.ActionInvoker.execute(), beseenium.controller.ActionFactory.ActionFactory.makeAction(), beseenium.model.ActionInvoker.remove(), and beseenium.model.ActionInvoker.size().
Referenced by beseenium.view.helpers.EmergencyShutdown.execute(), and beseenium.view.URLHandler.shutdown().
List<String> beseenium.controller.Test.executeActions () throws ActionDataException, ActionException
executes all actions in this test, in the sequence they were added
Returns
List<String> containing the results of each action
Exceptions
ActionDataException
ActionException
Definition at line 119 of file Test.java.
References beseenium.model.ActionInvoker.execute().
Referenced by beseenium.view.URLHandler.handleURL().
void beseenium.controller.Test.removeAction (int actionToRemove)
remove an action from this test.
Parameters
actionToRemove the index of the action to be removed from the test
Definition at line 108 of file Test.java.
References beseenium.model.ActionInvoker.remove().
void beseenium.controller.Test.setBrowser (String browserDriver) throws ActionDataException
Set the browser that you want this test to run on.
Parameters
browserDriver
Exceptions
ActionDataException
Definition at line 72 of file Test.java.
References beseenium.controller.ActionDataFactory.ActionDataFactory.makeActionData().
Referenced by beseenium.view.URLHandler.handleBrowser().
Member Data Documentation
ActionDataFactory beseenium.controller.Test.actionDataFactory private
reference to internal ActionDataFactory
Definition at line 44 of file Test.java.
ActionFactory beseenium.controller.Test.actionFactory private
reference to internal ActionFactory
Definition at line 42 of file Test.java.
ActionInvoker beseenium.controller.Test.invoker private
reference to Action Invoker.
Definition at line 46 of file Test.java.
The documentation for this class was generated from the following file:
Test.java