BeSeenium: beseenium.view.URLHandler.handleAddActions
String beseenium.view.URLHandler.handleAddActions (String addActions) private
takes an input from servlet(via handleURL method) in the form of string 'get' URL parameter 'addActions' and uses it to add actions to the test.
Parameters
addActions String of the form: "name+inputParam+optional|name+inputParam+optional|name+inputParam+optional|..."
Returns
String of the form: "ACTIONS ADDED:"+"[[action1, inputParam1, index1],[action2, inputParam2, index2]...[actionN, inputParamN, indexN]]
Definition at line 159 of file URLHandler.java.
References beseenium.controller.Test.addAction(), beseenium.view.URLHandler.shutdown(), and beseenium.view.URLHandler.splitString().
Referenced by beseenium.view.URLHandler.handleURL().