BeSeenium: beseenium.view.outputHandlers.OutputHandler Class Reference
beseenium.view.outputHandlers.OutputHandler Class Reference
This takes an array of AbstractTestRequests and uses it to generate output in various forms.
Public Member Functions
OutputHandler (Test test)
default constructor
void setRequests (Map< String, AbstractTestRequest > requests)
Sets the map of Test Requests to distribute to the various chains of responsibility.
void setSuccessor (AbstractRequestHandler successor)
List< String > handleRequests (String id)
Private Member Functions
boolean checkListForERROR (List< String > stringList)
checks to see if a List<String> contains the string "ERROR" in it
Private Attributes
Map< AbstractTestRequest, AbstractRequestHandler > successorMap
map of possible chains of responsibility to follow depending on the type of TestRequest
AbstractRequestHandler successor
The actual chain of responsibility to follow.
Map< String, AbstractTestRequest > requestMap
map of string descriptors to AbstractTestRequests
Test test
class copy of test to be used
Detailed Description
This takes an array of AbstractTestRequests and uses it to generate output in various forms.
Logically it is a specialisation of the AbstractRequestHandler type but contains an extra method setRequests() which allows it to distribute the requests contained in this array to chains of responsibility specific to that request type. It is also the client of all request chains of responsibility. As well as this, its handleRequests() method has no parameter, so while it is logically an AbstractRequestHandler it is not part of that inheritance hierarchy.
it is responsible for deciding the order in which the specific requests are passed to their handlers, however it is left to the root handler of individual chains to decide the order in which request specific handlers are called.
Author
Jan P.C. Hanson
Definition at line 49 of file OutputHandler.java.
Constructor & Destructor Documentation
beseenium.view.outputHandlers.OutputHandler.OutputHandler (Test test)
default constructor
Definition at line 63 of file OutputHandler.java.
References beseenium.view.outputHandlers.OutputHandler.test.
Member Function Documentation
boolean beseenium.view.outputHandlers.OutputHandler.checkListForERROR (List< String > stringList) private
checks to see if a List<String> contains the string "ERROR" in it
Parameters
stringList the List<String> to check
Returns
true if the list contains the String "ERROR", false if not.
Definition at line 154 of file OutputHandler.java.
Referenced by beseenium.view.outputHandlers.OutputHandler.handleRequests().
List<String> beseenium.view.outputHandlers.OutputHandler.handleRequests (String id)
Definition at line 99 of file OutputHandler.java.
References beseenium.view.outputHandlers.OutputHandler.checkListForERROR(), beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler.handleRequest(), beseenium.view.outputHandlers.OutputHandler.setSuccessor(), and beseenium.view.outputHandlers.OutputHandler.test.
Referenced by beseenium.view.BeSeeniumServlet.doGet().
void beseenium.view.outputHandlers.OutputHandler.setRequests (Map< String, AbstractTestRequest > requests)
Sets the map of Test Requests to distribute to the various chains of responsibility.
Parameters
requests
Definition at line 74 of file OutputHandler.java.
Referenced by beseenium.view.BeSeeniumServlet.doGet().
void beseenium.view.outputHandlers.OutputHandler.setSuccessor (AbstractRequestHandler successor)
Definition at line 86 of file OutputHandler.java.
References beseenium.view.outputHandlers.OutputHandler.successor.
Referenced by beseenium.view.outputHandlers.OutputHandler.handleRequests().
Member Data Documentation
Map<String, AbstractTestRequest> beseenium.view.outputHandlers.OutputHandler.requestMap private
map of string descriptors to AbstractTestRequests
Definition at line 56 of file OutputHandler.java.
AbstractRequestHandler beseenium.view.outputHandlers.OutputHandler.successor private
The actual chain of responsibility to follow.
Definition at line 54 of file OutputHandler.java.
Referenced by beseenium.view.outputHandlers.OutputHandler.setSuccessor().
Map<AbstractTestRequest, AbstractRequestHandler> beseenium.view.outputHandlers.OutputHandler.successorMap private
map of possible chains of responsibility to follow depending on the type of TestRequest
Definition at line 52 of file OutputHandler.java.
Test beseenium.view.outputHandlers.OutputHandler.test private
class copy of test to be used
Definition at line 58 of file OutputHandler.java.
Referenced by beseenium.view.outputHandlers.OutputHandler.handleRequests(), and beseenium.view.outputHandlers.OutputHandler.OutputHandler().
The documentation for this class was generated from the following file:
OutputHandler.java