BeSeenium: beseenium.view.helpers.StringSplit Class Reference
beseenium.view.helpers.StringSplit Class Reference
helper class that splits a string into an appropriate 2d array of strings.
Public Member Functions
StringSplit ()
default constructor
String[][] urlSplitString (String stringToSplit)
split a string of the form "V01 V02 ... V0n|V11 V12 ... V1n|Vm1 Vm2 ... Vmn" into a 2d String array of the form {{V01,V02...V0n},{V11,V12...V1n}...{Vm1, Vm2...
Static Public Member Functions
static String[][] generic2d (String stringToSplit, String split1Regex, String split2Regex)
split a string according to 2 delimiters, produces a 2d array
Detailed Description
helper class that splits a string into an appropriate 2d array of strings.
Author
Jan P.C. Hanson
Definition at line 24 of file StringSplit.java.
Constructor & Destructor Documentation
beseenium.view.helpers.StringSplit.StringSplit ()
default constructor
Definition at line 29 of file StringSplit.java.
Member Function Documentation
static String [][] beseenium.view.helpers.StringSplit.generic2d (String stringToSplit, String split1Regex, String split2Regex) static
split a string according to 2 delimiters, produces a 2d array
Parameters
stringToSplit the string to split
split1Regex first string to split at
split2Regex second string to split at
Returns
String[][] of the form {{V01,V02...V0n},{V11,V12...V1n}...{Vm1, Vm2... Vmn}}
Definition at line 59 of file StringSplit.java.
Referenced by beseenium.view.outputHandlers.compositors.AddActionCompositor.composite(), and beseenium.view.outputHandlers.compositors.CapabilitiesCompositor.composite().
String [][] beseenium.view.helpers.StringSplit.urlSplitString (String stringToSplit)
split a string of the form "V01 V02 ... V0n|V11 V12 ... V1n|Vm1 Vm2 ... Vmn" into a 2d String array of the form {{V01,V02...V0n},{V11,V12...V1n}...{Vm1, Vm2...
Vmn}}
Parameters
stringToSplit string of the form "V01 V02 ... V0n|V11 V12:... V1n|Vm1 Vm2 ... Vmn"
Returns
String[][] of the form {{V01,V02...V0n},{V11,V12...V1n}...{Vm1, Vm2... Vmn}}
Definition at line 38 of file StringSplit.java.
Referenced by beseenium.view.inputHandlers.requests.AddActionsRequest.executeRequest(), and beseenium.view.inputHandlers.requests.CapabilitiesRequest.executeRequest().
The documentation for this class was generated from the following file:
StringSplit.java