BeSeenium: beseenium.controller.Test.addAction
void beseenium.controller.Test.addAction (String actionName, String inputParameter, int optionalIndex) throws ActionFactoryException
Add an action to this test.
Parameters
actionName the name of the Action to add
inputParameter the input parameter (if applicable) of the action to add
optionalIndex an optional index (if applicable) to specify the element that this action will be performed on(assuming one of the previous actions was a FindElement action)
Exceptions
ActionFactoryException
Definition at line 98 of file Test.java.
References beseenium.model.ActionInvoker.add(), and beseenium.controller.ActionFactory.ActionFactory.makeAction().
Referenced by beseenium.view.URLHandler.handleAddActions().