BeSeenium: beseenium.model.ActionInvoker Class Reference
beseenium.model.ActionInvoker Class Reference
This class acts as the invoker in a GOF command style pattern.
Public Member Functions
ActionInvoker (ActionData actionData) throws ActionDataException
constructor, takes an ActionData(one that has been populated with a WebDriver, if it is not populated then you will run into problems down the line as the execute method requires one), and instantiates internal variables.
void add (AbstractAction action, String inputParam, int n)
Adds an abstract action to the action queue, each action has an input parameter and an index n.
void remove (int actionToRemove)
removes the last Action and associated parameters
List< String > execute () throws ActionDataException, ActionException
iterates through the commands stored in the list and executes
int size ()
get the current size of the invoker
Private Attributes
List< AbstractAction > actions
List< String > inputParams
List< Integer > optionalIndex
WebDriver driver
Detailed Description
This class acts as the invoker in a GOF command style pattern.
It stores and tries to execute a series of Actions loaded at runtime.
Author
JPC Hanson
Definition at line 33 of file ActionInvoker.java.
Constructor & Destructor Documentation
beseenium.model.ActionInvoker.ActionInvoker (ActionData actionData) throws ActionDataException
constructor, takes an ActionData(one that has been populated with a WebDriver, if it is not populated then you will run into problems down the line as the execute method requires one), and instantiates internal variables.
Exceptions
ActionDataException
Definition at line 47 of file ActionInvoker.java.
Member Function Documentation
void beseenium.model.ActionInvoker.add (AbstractAction action, String inputParam, int n)
Adds an abstract action to the action queue, each action has an input parameter and an index n.
Parameters
action an AbstractAction derived type.
inputParam dependant on the Action being performed.
n dependant on the Action being performed.
Definition at line 62 of file ActionInvoker.java.
Referenced by beseenium.controller.Test.addAction(), and beseenium.controller.Test.emergencyShutdown().
List<String> beseenium.model.ActionInvoker.execute () throws ActionDataException, ActionException
iterates through the commands stored in the list and executes
Returns
List<String> the results of the various actions, to be used in reporting.
Exceptions
ActionException
ActionDataException
Definition at line 87 of file ActionInvoker.java.
References beseenium.model.action.AbstractAction.execute(), beseenium.model.action.AbstractAction.getActionData(), beseenium.model.actionData.ActionData.setDriver(), and beseenium.model.actionData.ActionData.setInputParam().
Referenced by beseenium.controller.Test.emergencyShutdown(), and beseenium.controller.Test.executeActions().
void beseenium.model.ActionInvoker.remove (int actionToRemove)
removes the last Action and associated parameters
Parameters
actionToRemove the action to remove with 0 being the first action
Definition at line 73 of file ActionInvoker.java.
Referenced by beseenium.controller.Test.emergencyShutdown(), and beseenium.controller.Test.removeAction().
int beseenium.model.ActionInvoker.size ()
get the current size of the invoker
Returns
int representation of size.
Definition at line 112 of file ActionInvoker.java.
Referenced by beseenium.controller.Test.emergencyShutdown().
Member Data Documentation
List<AbstractAction> beseenium.model.ActionInvoker.actions private
Definition at line 35 of file ActionInvoker.java.
WebDriver beseenium.model.ActionInvoker.driver private
Definition at line 38 of file ActionInvoker.java.
List<String> beseenium.model.ActionInvoker.inputParams private
Definition at line 36 of file ActionInvoker.java.
List<Integer> beseenium.model.ActionInvoker.optionalIndex private
Definition at line 37 of file ActionInvoker.java.
The documentation for this class was generated from the following file:
ActionInvoker.java