BeSeenium: beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler Class Reference
beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler Class Reference abstract
abstract base for a chain of responsibility that takes abstractTestRequests and uses them to generate output in various forms: log messages, User messages, as well as taking care of exception handling.
Public Member Functions
void setSuccessor (AbstractRequestHandler successor)
sets the next concrete request handler in the chain.
abstract String handleRequest (AbstractTestRequest request, Test test)
provides implementation to handle the request.
Protected Attributes
AbstractRequestHandler successor
reference to the successor object
Detailed Description
abstract base for a chain of responsibility that takes abstractTestRequests and uses them to generate output in various forms: log messages, User messages, as well as taking care of exception handling.
Author
Jan P.C. Hanson
Definition at line 27 of file AbstractRequestHandler.java.
Member Function Documentation
abstract String beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler.handleRequest (AbstractTestRequest request, Test test) abstract
provides implementation to handle the request.
Returns
Referenced by beseenium.view.outputHandlers.OutputHandler.handleRequests().
void beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler.setSuccessor (AbstractRequestHandler successor)
sets the next concrete request handler in the chain.
Parameters
successor the next handler in the chain
Definition at line 36 of file AbstractRequestHandler.java.
References beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler.successor.
Referenced by beseenium.view.outputHandlers.requestHandlers.browserHandlers.RootBrowserHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.RootAddActionsHandler.handleRequest(), beseenium.view.outputHandlers.requestHandlers.executeHandlers.RootExecuteHandler.handleRequest(), and beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.RootCapabilitiesHandler.handleRequest().
Member Data Documentation
AbstractRequestHandler beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler.successor protected
reference to the successor object
Definition at line 30 of file AbstractRequestHandler.java.
Referenced by beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler.setSuccessor().
The documentation for this class was generated from the following file:
AbstractRequestHandler.java