BeSeenium: beseenium.view.HttpServer Class Reference
beseenium.view.HttpServer Class Reference
This is the embedded Jetty Web Server.
Static Public Member Functions
static void launch (int portNumber)
launches the embedded webserver on the specified port number.
Static Private Member Functions
static ContextHandler setUpServletHandler ()
do setup for the servlet handler
static ContextHandler setUpGuiHandler () throws MalformedURLException
do setup for the static resource handler
Static Private Attributes
static final Logger logger = LogManager.getLogger("BeSeenium.HttpServer")
Detailed Description
This is the embedded Jetty Web Server.
Author
Jan P.C. Hanson
Definition at line 37 of file HttpServer.java.
Member Function Documentation
static void beseenium.view.HttpServer.launch (int portNumber) static
launches the embedded webserver on the specified port number.
Parameters
portNumber the portnumber for the server to listen on.
Definition at line 44 of file HttpServer.java.
References beseenium.view.HttpServer.setUpGuiHandler(), and beseenium.view.HttpServer.setUpServletHandler().
Referenced by beseenium.Main.main().
static ContextHandler beseenium.view.HttpServer.setUpGuiHandler () throws MalformedURLException static private
do setup for the static resource handler
Returns
ContextHandler for the static resource handler
Definition at line 92 of file HttpServer.java.
Referenced by beseenium.view.HttpServer.launch().
static ContextHandler beseenium.view.HttpServer.setUpServletHandler () static private
do setup for the servlet handler
Returns
ContextHandler for the servlet
Definition at line 77 of file HttpServer.java.
Referenced by beseenium.view.HttpServer.launch().
Member Data Documentation
final Logger beseenium.view.HttpServer.logger = LogManager.getLogger("BeSeenium.HttpServer") static private
Definition at line 39 of file HttpServer.java.
The documentation for this class was generated from the following file:
HttpServer.java