BeSeenium: beseenium.view.outputHandlers.requestHandlers.addActionHandlers.RootAddActionsHandler Class Reference
beseenium.view.outputHandlers.requestHandlers.addActionHandlers.RootAddActionsHandler Class Reference
This class is the root of the addAction chain of responsibility, it takes care of defining the chain and, assuming the request fails, passing it to the first handler in the chain.
Public Member Functions
String handleRequest (AbstractTestRequest request, Test test)
Public Member Functions inherited from beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler
void setSuccessor (AbstractRequestHandler successor)
sets the next concrete request handler in the chain.
abstract String handleRequest (AbstractTestRequest request, Test test)
provides implementation to handle the request.
Additional Inherited Members
Protected Attributes inherited from beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler
AbstractRequestHandler successor
reference to the successor object
Detailed Description
This class is the root of the addAction chain of responsibility, it takes care of defining the chain and, assuming the request fails, passing it to the first handler in the chain.
The request then propagates down the chain until it gets handled, or in the worst case scenario, drops off the end of the chain without being handled.
Author
Jan P.C. Hanson
Definition at line 30 of file RootAddActionsHandler.java.
Member Function Documentation
String beseenium.view.outputHandlers.requestHandlers.addActionHandlers.RootAddActionsHandler.handleRequest (AbstractTestRequest request, Test test)
Definition at line 41 of file RootAddActionsHandler.java.
References beseenium.view.inputHandlers.requests.AbstractTestRequest.executeRequest(), beseenium.view.outputHandlers.requestHandlers.addActionHandlers.BadlyFormattedActionHandler.handleRequest(), and beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler.setSuccessor().
The documentation for this class was generated from the following file:
RootAddActionsHandler.java