BeSeenium: beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.RootCapabilitiesHandler Class Reference
beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.RootCapabilitiesHandler Class Reference
Public Member Functions
RootCapabilitiesHandler ()
String handleRequest (AbstractTestRequest request, Test test)
Public Member Functions inherited from beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler
void setSuccessor (AbstractRequestHandler successor)
abstract String handleRequest (AbstractTestRequest request, Test test)
Additional Inherited Members
Protected Attributes inherited from beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler
AbstractRequestHandler successor
Detailed Description
This class is the root of the capabilities chain of responsibility, it takes care of defining the chain and, assuming the request fails, passing it to the first handler in the chain. The request then propagates down the chain until it gets handled, or in the worst case scenario, drops off the end of the chain without being handled.
Author
Jan P.C. Hanson
Definition at line 31 of file RootCapabilitiesHandler.java.
Constructor & Destructor Documentation
beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.RootCapabilitiesHandler.RootCapabilitiesHandler ()
default ctor
Definition at line 36 of file RootCapabilitiesHandler.java.
Member Function Documentation
String beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.RootCapabilitiesHandler.handleRequest (AbstractTestRequest request, Test test)
Definition at line 46 of file RootCapabilitiesHandler.java.
References beseenium.view.inputHandlers.requests.AbstractTestRequest.executeRequest(), beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.EmptyCapsParamHandler.handleRequest(), and beseenium.view.outputHandlers.requestHandlers.AbstractRequestHandler.setSuccessor().
The documentation for this class was generated from the following file:
src/beseenium/view/outputHandlers/requestHandlers/capabilitiesHandlers/RootCapabilitiesHandler.java