BeSeenium: beseenium.view.inputHandlers.InputHandler Class Reference
beseenium.view.inputHandlers.InputHandler Class Reference
Public Member Functions
InputHandler ()
Map< String, AbstractTestRequest > handleInput (String caps, String brwsr, String actns)
AbstractTestRequest getRequest (String requestType)
Private Member Functions
AbstractTestRequest handleCapabilities (String caps)
AbstractTestRequest handleBrowser (String brwsr)
AbstractTestRequest handleAddActions (String actns)
AbstractTestRequest handleExecuteRequest ()
Private Attributes
Map< String, AbstractTestRequest > testRequests
Detailed Description
This class is responsible for taking the input, in the form of URL parameters passed in from the servlet, and turning them into AbstractTestRequest derived objects that can then be passed to the output handler to give useable results.
Author
Jan P.C. Hanson
Definition at line 36 of file InputHandler.java.
Constructor & Destructor Documentation
beseenium.view.inputHandlers.InputHandler.InputHandler ()
default constructor.
Definition at line 44 of file InputHandler.java.
Member Function Documentation
AbstractTestRequest beseenium.view.inputHandlers.InputHandler.getRequest (String requestType)
retrieves a request
Parameters
requestType string representing the request: capabilities/browser/actions/execute
Returns
AbstractTestRequest
Definition at line 75 of file InputHandler.java.
AbstractTestRequest beseenium.view.inputHandlers.InputHandler.handleAddActions (String actns) private
generates a AddActionRequest
Parameters
actns the actions string
Returns
AddActionRequest
Definition at line 105 of file InputHandler.java.
Referenced by beseenium.view.inputHandlers.InputHandler.handleInput().
AbstractTestRequest beseenium.view.inputHandlers.InputHandler.handleBrowser (String brwsr) private
generates a BrowserRequest
Parameters
brwsr the browser string
Returns
BrowserRequest
Definition at line 95 of file InputHandler.java.
Referenced by beseenium.view.inputHandlers.InputHandler.handleInput().
AbstractTestRequest beseenium.view.inputHandlers.InputHandler.handleCapabilities (String caps) private
generates a CapabilitiesRequest
Parameters
caps the capabilities string
Returns
CapabilitiesRequest
Definition at line 85 of file InputHandler.java.
Referenced by beseenium.view.inputHandlers.InputHandler.handleInput().
AbstractTestRequest beseenium.view.inputHandlers.InputHandler.handleExecuteRequest () private
generates an ExecuteRequest
Returns
ExecuteRequest
Definition at line 114 of file InputHandler.java.
Referenced by beseenium.view.inputHandlers.InputHandler.handleInput().
Map<String, AbstractTestRequest> beseenium.view.inputHandlers.InputHandler.handleInput (String caps, String brwsr, String actns)
Generates a map of string descriptors to requests from the given parameters, ending with a request to execute the test. keys are "capabilities", "browser", "actions", "execute"
Parameters
caps the capabilities passed in as a string.
brwsr the browser passed in as a string.
actns the actions to add passed in as a string.
Returns
Map<String, AbstractTestRequest> addressable by the strings: capabilities, browser, actions & execute.
Definition at line 60 of file InputHandler.java.
References beseenium.view.inputHandlers.InputHandler.handleAddActions(), beseenium.view.inputHandlers.InputHandler.handleBrowser(), beseenium.view.inputHandlers.InputHandler.handleCapabilities(), beseenium.view.inputHandlers.InputHandler.handleExecuteRequest(), and beseenium.view.inputHandlers.InputHandler.testRequests.
Referenced by beseenium.view.BeSeeniumServlet.doGet().
Member Data Documentation
Map<String, AbstractTestRequest> beseenium.view.inputHandlers.InputHandler.testRequests private
map of Strings to AbstractTestRequest's
Definition at line 39 of file InputHandler.java.
Referenced by beseenium.view.inputHandlers.InputHandler.handleInput().
The documentation for this class was generated from the following file:
src/beseenium/view/inputHandlers/InputHandler.java