.TH "navigateActions Directory Reference" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
navigateActions Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMakeNavigateBack\&.java\fP"
.br
.ti -1c
.RI "file \fBMakeNavigateForward\&.java\fP"
.br
.ti -1c
.RI "file \fBMakeRefreshPage\&.java\fP"
.br
.ti -1c
.RI "file \fBcontroller/ActionFactory/navigateActions/package-info\&.java\fP"
.br
.in -1c
