.TH "action Directory Reference" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
action Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBelementActions\fP"
.br
.ti -1c
.RI "directory \fBfindElementsBy\fP"
.br
.ti -1c
.RI "directory \fBnavigateActions\fP"
.br
.ti -1c
.RI "directory \fBpageActions\fP"
.br
.ti -1c
.RI "directory \fBswitchActions\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAbstractAction\&.java\fP"
.br
.ti -1c
.RI "file \fBmodel/action/package-info\&.java\fP"
.br
.ti -1c
.RI "file \fBResetActionData\&.java\fP"
.br
.in -1c
