.TH "outputHandlers Directory Reference" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
outputHandlers Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcompositors\fP"
.br
.ti -1c
.RI "directory \fBformatters\fP"
.br
.ti -1c
.RI "directory \fBrequestHandlers\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBOutputHandler\&.java\fP"
.br
.ti -1c
.RI "file \fBview/outputHandlers/package-info\&.java\fP"
.br
.in -1c
