.TH "exceptions Directory Reference" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exceptions Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBactionDataExceptions\fP"
.br
.ti -1c
.RI "directory \fBactionExceptions\fP"
.br
.ti -1c
.RI "directory \fBtestExceptions\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBeSeeniumException\&.java\fP"
.br
.ti -1c
.RI "file \fBexceptions/package-info\&.java\fP"
.br
.in -1c
