.TH "pageActions Directory Reference" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pageActions Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMakeBrowserQuit\&.java\fP"
.br
.ti -1c
.RI "file \fBMakeGetPageSrc\&.java\fP"
.br
.ti -1c
.RI "file \fBMakeGetTitle\&.java\fP"
.br
.ti -1c
.RI "file \fBMakeGetURL\&.java\fP"
.br
.ti -1c
.RI "file \fBMakePageClose\&.java\fP"
.br
.ti -1c
.RI "file \fBMakePageGet\&.java\fP"
.br
.ti -1c
.RI "file \fBcontroller/ActionFactory/pageActions/package-info\&.java\fP"
.br
.in -1c
