.TH "AbstractRequestHandler.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractRequestHandler.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.view\&.outputHandlers\&.requestHandlers\&.AbstractRequestHandler\fP"
.br
.RI "\fIabstract base for a chain of responsibility that takes abstractTestRequests and uses them to generate output in various forms: log messages, User messages, as well as taking care of exception handling\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.view\&.outputHandlers\&.requestHandlers\fP"
.br
.RI "\fIThis is the root package for all request handlers in the \fBAbstractRequestHandler\fP inheritance hierarchy\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
