.TH "AbstractOutputFormatter.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractOutputFormatter.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBbeseenium\&.view\&.outputHandlers\&.formatters\&.AbstractOutputFormatter\fP"
.br
.RI "\fIInterface that all output formatter classes should subscribe to, allowing the servlet to request an appropriate output format specific to a users request\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.view\&.outputHandlers\&.formatters\fP"
.br
.RI "\fIThis package provides objects that modify the text output of the \fBOutputHandler\fP after AbstractTestRequest's have been processed, into a variety of more usable forms: JSON, XML, etc\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
