.TH "ActionInvoker.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionInvoker.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.model\&.ActionInvoker\fP"
.br
.RI "\fIThis class acts as the invoker in a GOF command style pattern\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.model\fP"
.br
.RI "\fIThis is the root package for the Model module of the BeSeenium application, it contains all the classes related to the data model\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
