.TH "ActionFactory.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionFactory.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.controller\&.ActionFactory\&.ActionFactory\fP"
.br
.RI "\fIthis class is a factory for creating actions, it uses a factory method style pattern and a map implementation\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.controller\&.ActionFactory\fP"
.br
.RI "\fIThis is the root package for the \fBActionFactory\fP implementation, similarly to the \fBActionDataFactory\fP, it is a factory method style implementation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
