.TH "ActionDataException.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionDataException.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.exceptions\&.actionDataExceptions\&.ActionDataException\fP"
.br
.RI "\fIException applicable to ActionData\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.exceptions\&.actionDataExceptions\fP"
.br
.RI "\fIThis package contains Exceptions related to ActionData objects, and their related objects\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
