.TH "ActionData.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionData.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.model\&.actionData\&.ActionData\fP"
.br
.RI "\fIThis class encapsulates the data needed to perform an action into 4 distinct areas: 
.br

.br
 \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.model\&.actionData\fP"
.br
.RI "\fIThis package contains the \fBActionData\fP and any related classes\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
