.TH "AddActionsRequest.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddActionsRequest.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.view\&.inputHandlers\&.requests\&.AddActionsRequest\fP"
.br
.RI "\fIrepresents a request to add a series of actions to a test\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.view\&.inputHandlers\&.requests\fP"
.br
.RI "\fIThis package contains the classes necessary for creating request objects\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
