.TH "BadlyFormattedActionHandler.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BadlyFormattedActionHandler.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.view\&.outputHandlers\&.requestHandlers\&.addActionHandlers\&.BadlyFormattedActionHandler\fP"
.br
.RI "\fIThis represents a handler for the case where the user has entered a badly formatted value for the addAction parameter, if this is the case the request will throw a TestException, which is caught by this class and notifies the user of their mistake\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.view\&.outputHandlers\&.requestHandlers\&.addActionHandlers\fP"
.br
.RI "\fIThis package contains all classes relevant to the chain of responsibility that processes the 'addActions' url query string\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
