.TH "beseenium.view.outputHandlers.formatters" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.outputHandlers.formatters \- This package provides objects that modify the text output of the \fBOutputHandler\fP after AbstractTestRequest's have been processed, into a variety of more usable forms: JSON, XML, etc\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBAbstractOutputFormatter\fP"
.br
.RI "\fIInterface that all output formatter classes should subscribe to, allowing the servlet to request an appropriate output format specific to a users request\&. \fP"
.ti -1c
.RI "class \fBBasicFormatter\fP"
.br
.RI "\fICopyright(C) 2015 Jan P\&.C\&. \fP"
.ti -1c
.RI "class \fBJsonFormatter\fP"
.br
.RI "\fIThis class provides methods to transform strings into JSON format\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package provides objects that modify the text output of the \fBOutputHandler\fP after AbstractTestRequest's have been processed, into a variety of more usable forms: JSON, XML, etc\&. 

So that the user is presented with output that can then be easily presented and manipulated by a client-side frontend\&.
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
