.TH "beseenium.view.helpers.URLStringSplit" 3 "Thu Sep 10 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.helpers.URLStringSplit \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBURLStringSplit\fP ()"
.br
.ti -1c
.RI "String[][] \fBsplitString\fP (String stringToSplit)"
.br
.in -1c
.SH "Detailed Description"
.PP 
helper class that splits a string into an appropriate 2d array of strings\&. 
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 23 of file URLStringSplit\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.view\&.helpers\&.URLStringSplit\&.URLStringSplit ()"
default constructor 
.PP
Definition at line 28 of file URLStringSplit\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String [][] beseenium\&.view\&.helpers\&.URLStringSplit\&.splitString (String stringToSplit)"
split a string of the form 'V01:V02:\&.\&.\&.:V0n|V11:V12:\&.\&.\&.:V1n|Vm1:Vm2:\&.\&.\&.:Vmn' into a 2d String array of the form {{V01,V02\&.\&.\&.V0n},{V11,V12\&.\&.\&.V1n}\&.\&.\&.{Vm1, Vm2\&.\&.\&. Vmn}} 
.PP
\fBParameters:\fP
.RS 4
\fIstringToSplit\fP string of the form 'V01:V02:\&.\&.\&.:V0n|V11:V12:\&.\&.\&.:V1n|Vm1:Vm2:\&.\&.\&.:Vmn' 
.RE
.PP
\fBReturns:\fP
.RS 4
String[][] of the form {{V01,V02\&.\&.\&.V0n},{V11,V12\&.\&.\&.V1n}\&.\&.\&.{Vm1, Vm2\&.\&.\&. Vmn}} 
.RE
.PP

.PP
Definition at line 37 of file URLStringSplit\&.java\&.
.PP
Referenced by beseenium\&.view\&.inputHandlers\&.requests\&.AddActionsRequest\&.executeRequest(), and beseenium\&.view\&.inputHandlers\&.requests\&.CapabilitiesRequest\&.executeRequest()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
