.TH "BeSeenium" 3 "Sat Sep 12 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BeSeenium \- Manual 
title
.PP
.IP "\(bu" 2
\fBsub page 1\fP
.IP "\(bu" 2
\fBsub page 2\fP
.PP
.SH "first section page1"
.PP
.SS "first sub section page1"
.SS "first sub sub section page1"
.SH "second section page1"
.PP
.SS "second sub section page1"
.SS "second sub sub section page1"

