.TH "beseenium.controller.ActionFactory.findElementsBy" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.controller.ActionFactory.findElementsBy \- This package contains all the MakeData derived classes necessary for the \fBActionFactory\fP to create FindElementBy\&.\&.\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMakeFindElementsByClass\fP"
.br
.RI "\fICreates a new FindElementsByClass action\&. \fP"
.ti -1c
.RI "class \fBMakeFindElementsByCss\fP"
.br
.RI "\fICreates a new FindElementsByCss action\&. \fP"
.ti -1c
.RI "class \fBMakeFindElementsById\fP"
.br
.RI "\fIcreates a new FindElementsById action \fP"
.ti -1c
.RI "class \fBMakeFindElementsByLinkTxt\fP"
.br
.RI "\fIcreates a new FindElementsByLinkTxt action \fP"
.ti -1c
.RI "class \fBMakeFindElementsByName\fP"
.br
.RI "\fIcreates a new FindElementsByName action \fP"
.ti -1c
.RI "class \fBMakeFindElementsByPartialLinkTxt\fP"
.br
.RI "\fIcreates a new FindElementsByPartialLinkTxt action \fP"
.ti -1c
.RI "class \fBMakeFindElementsByTagName\fP"
.br
.RI "\fIcreates a new FindElementsByTagName action \fP"
.ti -1c
.RI "class \fBMakeFindElementsByXpath\fP"
.br
.RI "\fIcreates a new FindElementsByXpath action \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package contains all the MakeData derived classes necessary for the \fBActionFactory\fP to create FindElementBy\&.\&.\&. 

objects\&. 
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
