.TH "beseenium.exceptions.testExceptions.TestException" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.exceptions.testExceptions.TestException \- Exception that apply to Test's\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.exceptions\&.BeSeeniumException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestException\fP (String message)"
.br
.RI "\fIinstsnciate excecption with message \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTestException\fP ()"
.br
.RI "\fIdefault constructor \fP"
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = 2620333356090725352L"
.br
.RI "\fIneeded to avoid warning \fP"
.in -1c
.SH "Detailed Description"
.PP 
Exception that apply to Test's\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 25 of file TestException\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.exceptions\&.testExceptions\&.TestException\&.TestException ()\fC [protected]\fP"

.PP
default constructor 
.PP
Definition at line 35 of file TestException\&.java\&.
.SS "beseenium\&.exceptions\&.testExceptions\&.TestException\&.TestException (String message)"

.PP
instsnciate excecption with message 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP string to display 
.RE
.PP

.PP
Definition at line 44 of file TestException\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final long beseenium\&.exceptions\&.testExceptions\&.TestException\&.serialVersionUID = 2620333356090725352L\fC [static]\fP, \fC [private]\fP"

.PP
needed to avoid warning 
.PP
Definition at line 30 of file TestException\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
