.TH "beseenium.exceptions.actionExceptions.ActionException" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.exceptions.actionExceptions.ActionException \- exception applicable to Actions  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.exceptions\&.BeSeeniumException\fP\&.
.PP
Inherited by \fBbeseenium\&.exceptions\&.actionExceptions\&.ActionFactoryException\fP, \fBbeseenium\&.exceptions\&.actionExceptions\&.ClickException\fP, \fBbeseenium\&.exceptions\&.actionExceptions\&.NoSuchParameterException\fP, and \fBbeseenium\&.exceptions\&.actionExceptions\&.SubmitException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActionException\fP ()"
.br
.ti -1c
.RI "\fBActionException\fP (String message)"
.br
.RI "\fIinstsnciate excecption with message \fP"
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = -2121908009959867560L"
.br
.RI "\fISerialisation needed to avoid warnings\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
exception applicable to Actions 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 24 of file ActionException\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.exceptions\&.actionExceptions\&.ActionException\&.ActionException ()"

.PP
Definition at line 34 of file ActionException\&.java\&.
.SS "beseenium\&.exceptions\&.actionExceptions\&.ActionException\&.ActionException (String message)"

.PP
instsnciate excecption with message 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP string to display 
.RE
.PP

.PP
Definition at line 43 of file ActionException\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final long beseenium\&.exceptions\&.actionExceptions\&.ActionException\&.serialVersionUID = -2121908009959867560L\fC [static]\fP, \fC [private]\fP"

.PP
Serialisation needed to avoid warnings\&. 
.PP
Definition at line 30 of file ActionException\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
