.TH "beseenium.controller.ActionFactory.navigateActions" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.controller.ActionFactory.navigateActions \- This package contains all the MakeData derived classes needed for the \fBActionFactory\fP to create navigation type action objects\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMakeNavigateBack\fP"
.br
.RI "\fIcreates new NavigateBack action \fP"
.ti -1c
.RI "class \fBMakeNavigateForward\fP"
.br
.RI "\fIcreate new NavigateForwards action \fP"
.ti -1c
.RI "class \fBMakeRefreshPage\fP"
.br
.RI "\fIcreates a new RefreshPage action \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package contains all the MakeData derived classes needed for the \fBActionFactory\fP to create navigation type action objects\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
