.TH "beseenium.exceptions" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.exceptions \- This package is the root package for all custom BeSeenium exceptions, it contains the root of the \fBBeSeeniumException\fP inheritance hierarchy, all derived exceptions are located in sub-packages\&.  

.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBactionDataExceptions\fP"
.br
.RI "\fIThis package contains Exceptions related to ActionData objects, and their related objects\&. \fP"
.ti -1c
.RI "package \fBactionExceptions\fP"
.br
.RI "\fIThis package contains all exceptions relating to AbstractAction objects, their creation and their use\&. \fP"
.ti -1c
.RI "package \fBtestExceptions\fP"
.br
.RI "\fIThis package contains exceptions relevant to Test objects\&. \fP"
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBeSeeniumException\fP"
.br
.RI "\fICopyright(C) 2015 Jan P\&.C\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package is the root package for all custom BeSeenium exceptions, it contains the root of the \fBBeSeeniumException\fP inheritance hierarchy, all derived exceptions are located in sub-packages\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
