.TH "beseenium.Main" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.Main \- This is the main entry point for the program, initial setup and configuration done here\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.RI "\fIpasses the first command line argument to the http server, ostensibly the port number\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is the main entry point for the program, initial setup and configuration done here\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 28 of file Main\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void beseenium\&.Main\&.main (String[] args)\fC [static]\fP"

.PP
passes the first command line argument to the http server, ostensibly the port number\&. also does some setup for log4j async logger\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP command line arguments\&. 
.RE
.PP

.PP
Definition at line 36 of file Main\&.java\&.
.PP
References beseenium\&.view\&.HttpServer\&.launch()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
