.TH "beseenium.view.outputFormatters.CapabilitiesCompositor" 3 "Thu Sep 17 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.outputFormatters.CapabilitiesCompositor \- Copyright(C) 2015 Jan P\&.C\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.view\&.outputFormatters\&.AbstractCompositor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCapabilitiesCompositor\fP (\fBAbstractOutputFormatter\fP format)"
.br
.RI "\fIspecifies the format that the user wishes the output returned in e\&.g\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Copyright(C) 2015 Jan P\&.C\&. 

Hanson & BeSeen Marketing Ltd
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program\&. If not, see http://www.gnu.org/licenses/\&.
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 23 of file CapabilitiesCompositor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.view\&.outputFormatters\&.CapabilitiesCompositor\&.CapabilitiesCompositor (\fBAbstractOutputFormatter\fP format)"

.PP
specifies the format that the user wishes the output returned in e\&.g\&. JSON, XML, etc 
.PP
\fBParameters:\fP
.RS 4
\fIformat\fP the format that the user wishes the output returned in e\&.g\&. JSON, XML, etc 
.RE
.PP

.PP
Definition at line 30 of file CapabilitiesCompositor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
