.TH "beseenium.model.action.switchActions.SwitchToActiveElement" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.model.action.switchActions.SwitchToActiveElement \- this is a \fBSwitchToActiveElement\fP, it Switches to the element that currently has focus within the document currently 'switched to', or the body element if this cannot be detected\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.model\&.action\&.AbstractAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSwitchToActiveElement\fP (\fBActionData\fP \fBcontext\fP)"
.br
.RI "\fIconstructor, initialises Action using the ActionData passed in as a param \fP"
.ti -1c
.RI "String \fBexecute\fP (int n)  throws ActionDataException 	"
.br
.RI "\fIExecutes the switch to the currently active element\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
this is a \fBSwitchToActiveElement\fP, it Switches to the element that currently has focus within the document currently 'switched to', or the body element if this cannot be detected\&. 


.PP
\fBAuthor:\fP
.RS 4
JPC Hanson 
.RE
.PP

.PP
Definition at line 28 of file SwitchToActiveElement\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.model\&.action\&.switchActions\&.SwitchToActiveElement\&.SwitchToActiveElement (\fBActionData\fP context)"

.PP
constructor, initialises Action using the ActionData passed in as a param 
.PP
\fBParameters:\fP
.RS 4
\fIcontext\fP an ActionData 
.RE
.PP

.PP
Definition at line 34 of file SwitchToActiveElement\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.model\&.action\&.switchActions\&.SwitchToActiveElement\&.execute (int n) throws \fBActionDataException\fP"

.PP
Executes the switch to the currently active element\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP meaningless variable 
.RE
.PP
\fBReturns:\fP
.RS 4
String confirming the element that has been switched to 
.RE
.PP

.PP
Definition at line 43 of file SwitchToActiveElement\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
