.TH "beseenium.view.inputHandlers.requests" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.inputHandlers.requests \- This package contains the classes necessary for creating request objects\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractTestRequest\fP"
.br
.RI "\fIThis class is the abstract base class for a series of request objects relating to various parts of a test's functionality, e\&.g\&. \fP"
.ti -1c
.RI "class \fBAddActionsRequest\fP"
.br
.RI "\fIrepresents a request to add a series of actions to a test\&. \fP"
.ti -1c
.RI "class \fBBrowserRequest\fP"
.br
.RI "\fIThis class represents a request for a test to use a particular browser type\&. \fP"
.ti -1c
.RI "class \fBCapabilitiesRequest\fP"
.br
.RI "\fIrepresents a request for a particular set of capabilities\&. \fP"
.ti -1c
.RI "class \fBExecuteRequest\fP"
.br
.RI "\fIrepresents a request to execute the test\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package contains the classes necessary for creating request objects\&. 

These objects are part of the \fBAbstractTestRequest\fP inheritance hierarchy\&.
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
