.TH "beseenium.model.action.elementActions.GetAttribute" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.model.action.elementActions.GetAttribute \- This is a getAttribute action, it takes the input parameter from the ActionData object to perform this action so make sure that at the time of execution this reflects the attribute you wish to find the value of i\&.e\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.model\&.action\&.AbstractAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetAttribute\fP (\fBActionData\fP \fBcontext\fP)"
.br
.RI "\fIconstructor, initialises Action using the ActionData passed in as a param \fP"
.ti -1c
.RI "String \fBexecute\fP (int n)  throws ActionDataException, ActionException  	"
.br
.RI "\fIThis performs a getAttribute action\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is a getAttribute action, it takes the input parameter from the ActionData object to perform this action so make sure that at the time of execution this reflects the attribute you wish to find the value of i\&.e\&. 

'href' , 'class' , 'id' , etc\&. 
.PP
\fBAuthor:\fP
.RS 4
JPC Hanson 
.RE
.PP

.PP
Definition at line 33 of file GetAttribute\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.model\&.action\&.elementActions\&.GetAttribute\&.GetAttribute (\fBActionData\fP context)"

.PP
constructor, initialises Action using the ActionData passed in as a param 
.PP
\fBParameters:\fP
.RS 4
\fIcontext\fP an ActionData 
.RE
.PP

.PP
Definition at line 39 of file GetAttribute\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.model\&.action\&.elementActions\&.GetAttribute\&.execute (int n) throws \fBActionDataException\fP, \fBActionException\fP"

.PP
This performs a getAttribute action\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP the index of the element to get an attribute of (as taken from the ActionData) 
.RE
.PP
\fBReturns:\fP
.RS 4
String containing the value of the attribute set in the input parameter 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIActionDataException\fP 
.br
\fIActionException\fP 
.RE
.PP

.PP
Definition at line 50 of file GetAttribute\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
