.TH "beseenium.view.inputHandlers.requests.AddActionsRequest" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.inputHandlers.requests.AddActionsRequest \- represents a request to add a series of actions to a test\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.view\&.inputHandlers\&.requests\&.AbstractTestRequest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddActionsRequest\fP (String \fBrequestData\fP)"
.br
.RI "\fIcall super constructor passing in the appropriate request data\&. \fP"
.ti -1c
.RI "String \fBexecuteRequest\fP (\fBTest\fP test)  throws ActionDataException, NullPointerException, ActionFactoryException,  			NumberFormatException, TestException 	"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
represents a request to add a series of actions to a test\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 30 of file AddActionsRequest\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.view\&.inputHandlers\&.requests\&.AddActionsRequest\&.AddActionsRequest (String requestData)"

.PP
call super constructor passing in the appropriate request data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrequestData\fP 
.RE
.PP

.PP
Definition at line 36 of file AddActionsRequest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.view\&.inputHandlers\&.requests\&.AddActionsRequest\&.executeRequest (\fBTest\fP test) throws \fBActionDataException\fP, NullPointerException, \fBActionFactoryException\fP,  			NumberFormatException, \fBTestException\fP"

.PP
Definition at line 51 of file AddActionsRequest\&.java\&.
.PP
References beseenium\&.view\&.helpers\&.StringSplit\&.urlSplitString()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
