.TH "beseenium.model.action.ResetActionData" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.model.action.ResetActionData \- this resets various attributes of the ActionData  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.model\&.action\&.AbstractAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResetActionData\fP (\fBActionData\fP \fBcontext\fP)"
.br
.RI "\fIconstructor, initialises Action using the ActionData passed in as a param \fP"
.ti -1c
.RI "String \fBexecute\fP (int n)  throws NoSuchParameterException 	"
.br
.RI "\fIperforms the reset action data action\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
this resets various attributes of the ActionData 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 26 of file ResetActionData\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.model\&.action\&.ResetActionData\&.ResetActionData (\fBActionData\fP context)"

.PP
constructor, initialises Action using the ActionData passed in as a param 
.PP
\fBParameters:\fP
.RS 4
\fIcontext\fP an ActionData 
.RE
.PP

.PP
Definition at line 32 of file ResetActionData\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.model\&.action\&.ResetActionData\&.execute (int n) throws \fBNoSuchParameterException\fP"

.PP
performs the reset action data action\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP 0=reset WebElement, 1=reset inputParam, -1=reset all 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fINoSuchParameterException\fP 
.RE
.PP

.PP
Definition at line 40 of file ResetActionData\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
