.TH "beseenium.view.inputHandlers.requests.CapabilitiesRequest" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.inputHandlers.requests.CapabilitiesRequest \- represents a request for a particular set of capabilities\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.view\&.inputHandlers\&.requests\&.AbstractTestRequest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCapabilitiesRequest\fP (String \fBrequestData\fP)"
.br
.RI "\fIcall super constructor passing in the appropriate request data\&. \fP"
.ti -1c
.RI "String \fBexecuteRequest\fP (\fBTest\fP test)  throws ActionDataException, NullPointerException, TestException, MalformedURLException 	"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
represents a request for a particular set of capabilities\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 29 of file CapabilitiesRequest\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.view\&.inputHandlers\&.requests\&.CapabilitiesRequest\&.CapabilitiesRequest (String requestData)"

.PP
call super constructor passing in the appropriate request data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrequestData\fP 
.RE
.PP

.PP
Definition at line 35 of file CapabilitiesRequest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.view\&.inputHandlers\&.requests\&.CapabilitiesRequest\&.executeRequest (\fBTest\fP test) throws \fBActionDataException\fP, NullPointerException, \fBTestException\fP, MalformedURLException"

.PP
Definition at line 53 of file CapabilitiesRequest\&.java\&.
.PP
References beseenium\&.view\&.helpers\&.StringSplit\&.urlSplitString()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
