.TH "beseenium.controller.ActionFactory.elementActions.MakeGetAttribute" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.controller.ActionFactory.elementActions.MakeGetAttribute \- creates a new GetAttribute action  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.controller\&.ActionFactory\&.MakeAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMakeGetAttribute\fP (\fBActionDataFactory\fP adf)"
.br
.RI "\fIcall to super constructor \fP"
.ti -1c
.RI "\fBAbstractAction\fP \fBmakeAction\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
creates a new GetAttribute action 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 27 of file MakeGetAttribute\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.controller\&.ActionFactory\&.elementActions\&.MakeGetAttribute\&.MakeGetAttribute (\fBActionDataFactory\fP adf)"

.PP
call to super constructor 
.PP
\fBParameters:\fP
.RS 4
\fIadf\fP an \fBActionDataFactory\fP 
.RE
.PP

.PP
Definition at line 33 of file MakeGetAttribute\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAbstractAction\fP beseenium\&.controller\&.ActionFactory\&.elementActions\&.MakeGetAttribute\&.makeAction ()"

.PP
Definition at line 40 of file MakeGetAttribute\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
