.TH "beseenium.view.outputHandlers.compositors" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.outputHandlers.compositors \- This package holds the compositors which are used by the output handler to compose the result strings into the format requested by the user\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractCompositor\fP"
.br
.RI "\fICopyright(C) 2015 Jan P\&.C\&. \fP"
.ti -1c
.RI "class \fBAddActionCompositor\fP"
.br
.ti -1c
.RI "class \fBBrowserCompositor\fP"
.br
.RI "\fICopyright(C) 2015 Jan P\&.C\&. \fP"
.ti -1c
.RI "class \fBCapabilitiesCompositor\fP"
.br
.RI "\fICopyright(C) 2015 Jan P\&.C\&. \fP"
.ti -1c
.RI "class \fBExecuteCompositor\fP"
.br
.RI "\fICopyright(C) 2015 Jan P\&.C\&. \fP"
.ti -1c
.RI "class \fBRootCompositor\fP"
.br
.RI "\fICopyright(C) 2015 Jan P\&.C\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package holds the compositors which are used by the output handler to compose the result strings into the format requested by the user\&. 

The hierarchy is based around the \fBAbstractCompositor\fP abstract base class which provides default construction to the derived classes\&. Derived classes are specialised to individual result types i\&.e\&. execution results, addAction results, capability results and browser results\&.
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
