.TH "beseenium.controller.ActionFactory.pageActions" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.controller.ActionFactory.pageActions \- This package contains all the MakeData derived objects necessary for the \fBActionFactory\fP to create page-scoped actions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMakeBrowserQuit\fP"
.br
.RI "\fIcreates a new BrowserQuit action \fP"
.ti -1c
.RI "class \fBMakeGetPageSrc\fP"
.br
.RI "\fIcreates a new GetPageSrc action \fP"
.ti -1c
.RI "class \fBMakeGetTitle\fP"
.br
.RI "\fIcreates a new GetTitle action \fP"
.ti -1c
.RI "class \fBMakeGetURL\fP"
.br
.RI "\fIcreates a new GetURL action \fP"
.ti -1c
.RI "class \fBMakePageClose\fP"
.br
.RI "\fIcreates a new PageClose action \fP"
.ti -1c
.RI "class \fBMakePageGet\fP"
.br
.RI "\fIcreates a new PageGet object \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package contains all the MakeData derived objects necessary for the \fBActionFactory\fP to create page-scoped actions\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
