.TH "beseenium.model.action.pageActions.GetURL" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.model.action.pageActions.GetURL \- This is a \fBGetURL\fP Action, it retrieves the URL of the current page\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.model\&.action\&.AbstractAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetURL\fP (\fBActionData\fP \fBcontext\fP)"
.br
.RI "\fIconstructor, initialises Action using the ActionData passed in as a param \fP"
.ti -1c
.RI "String \fBexecute\fP (int n)  throws ActionDataException  	"
.br
.RI "\fIThis performs a \fBGetURL\fP action\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is a \fBGetURL\fP Action, it retrieves the URL of the current page\&. 


.PP
\fBAuthor:\fP
.RS 4
JPC Hanson 
.RE
.PP

.PP
Definition at line 25 of file GetURL\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.model\&.action\&.pageActions\&.GetURL\&.GetURL (\fBActionData\fP context)"

.PP
constructor, initialises Action using the ActionData passed in as a param 
.PP
\fBParameters:\fP
.RS 4
\fIcontext\fP an ActionData 
.RE
.PP

.PP
Definition at line 31 of file GetURL\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.model\&.action\&.pageActions\&.GetURL\&.execute (int n) throws \fBActionDataException\fP"

.PP
This performs a \fBGetURL\fP action\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP meaningless pass in any old value 
.RE
.PP
\fBReturns:\fP
.RS 4
String containing the URL of the current page 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIActionDataException\fP 
.RE
.PP

.PP
Definition at line 41 of file GetURL\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
