.TH "beseenium.exceptions.BeSeeniumException" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.exceptions.BeSeeniumException \- Copyright(C) 2015 Jan P\&.C\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.PP
Inherited by \fBbeseenium\&.exceptions\&.actionDataExceptions\&.ActionDataException\fP, \fBbeseenium\&.exceptions\&.actionExceptions\&.ActionException\fP, and \fBbeseenium\&.exceptions\&.testExceptions\&.TestException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBeSeeniumException\fP (String message)"
.br
.RI "\fIinstsnciate excecption with message \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBBeSeeniumException\fP ()"
.br
.RI "\fIdefault constructor \fP"
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = 5427176352533290074L"
.br
.RI "\fISerialisation needed to avoid warnings\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Copyright(C) 2015 Jan P\&.C\&. 

Hanson & BeSeen Marketing Ltd
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program\&. If not, see http://www.gnu.org/licenses/\&. the root class for the beseenium exception hierarchy 
.PP
\fBAuthor:\fP
.RS 4
JPC Hanson 
.RE
.PP

.PP
Definition at line 22 of file BeSeeniumException\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.exceptions\&.BeSeeniumException\&.BeSeeniumException ()\fC [protected]\fP"

.PP
default constructor 
.PP
Definition at line 32 of file BeSeeniumException\&.java\&.
.SS "beseenium\&.exceptions\&.BeSeeniumException\&.BeSeeniumException (String message)"

.PP
instsnciate excecption with message 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP string to display 
.RE
.PP

.PP
Definition at line 41 of file BeSeeniumException\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final long beseenium\&.exceptions\&.BeSeeniumException\&.serialVersionUID = 5427176352533290074L\fC [static]\fP, \fC [private]\fP"

.PP
Serialisation needed to avoid warnings\&. 
.PP
Definition at line 27 of file BeSeeniumException\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
