.TH "beseenium.controller.ActionDataFactory.MakeData" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.controller.ActionDataFactory.MakeData \- interface which describes a prototype for creating \fBMakeData\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbeseenium\&.controller\&.ActionDataFactory\&.ActionDataFactory\fP, \fBbeseenium\&.controller\&.ActionDataFactory\&.MakeFirefoxData\fP, and \fBbeseenium\&.controller\&.ActionDataFactory\&.MakeHtmlUnitDriverData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActionData\fP \fBmakeActionData\fP ()"
.br
.RI "\fIthe factory method that returns the ActionData specific to the derived type of MakeActionData\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
interface which describes a prototype for creating \fBMakeData\fP objects\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 24 of file MakeData\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBActionData\fP beseenium\&.controller\&.ActionDataFactory\&.MakeData\&.makeActionData ()"

.PP
the factory method that returns the ActionData specific to the derived type of MakeActionData\&. 
.PP
\fBReturns:\fP
.RS 4
ActionData appropriate to this type\&. 
.RE
.PP

.PP
Implemented in \fBbeseenium\&.controller\&.ActionDataFactory\&.ActionDataFactory\fP, \fBbeseenium\&.controller\&.ActionDataFactory\&.MakeFirefoxData\fP, and \fBbeseenium\&.controller\&.ActionDataFactory\&.MakeHtmlUnitDriverData\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
