.TH "beseenium.exceptions.testExceptions.TestAlreadyExistsException" 3 "Thu Sep 10 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.exceptions.testExceptions.TestAlreadyExistsException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.exceptions\&.testExceptions\&.TestException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestAlreadyExistsException\fP (String message)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTestAlreadyExistsException\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = -4809217893822758020L"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 23 of file TestAlreadyExistsException\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.exceptions\&.testExceptions\&.TestAlreadyExistsException\&.TestAlreadyExistsException ()\fC [protected]\fP"
default constructor 
.PP
Definition at line 33 of file TestAlreadyExistsException\&.java\&.
.SS "beseenium\&.exceptions\&.testExceptions\&.TestAlreadyExistsException\&.TestAlreadyExistsException (String message)"
instsnciate excecption with message 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP string to display 
.RE
.PP

.PP
Definition at line 42 of file TestAlreadyExistsException\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final long beseenium\&.exceptions\&.testExceptions\&.TestAlreadyExistsException\&.serialVersionUID = -4809217893822758020L\fC [static]\fP, \fC [private]\fP"
needed to avoid warnings 
.PP
Definition at line 28 of file TestAlreadyExistsException\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
