.TH "beseenium.model.actionData" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.model.actionData \- This package contains the \fBActionData\fP and any related classes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActionData\fP"
.br
.RI "\fIThis class encapsulates the data needed to perform an action into 4 distinct areas: 
.br

.br
 \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package contains the \fBActionData\fP and any related classes\&. 

That is any classes that are used to hold data that is needed for actions to be performed\&.
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
