.TH "beseenium.model.action.elementActions.Click" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.model.action.elementActions.Click \- This is a click action,\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.model\&.action\&.AbstractAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClick\fP (\fBActionData\fP \fBcontext\fP)"
.br
.RI "\fIconstructor, initialises Action using the ActionData passed in as a param \fP"
.ti -1c
.RI "String \fBexecute\fP (int n)  throws ActionDataException, ClickException  	"
.br
.RI "\fIThis performs the click action\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is a click action,\&. 


.PP
\fBAuthor:\fP
.RS 4
JPC Hanson 
.RE
.PP

.PP
Definition at line 33 of file Click\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.model\&.action\&.elementActions\&.Click\&.Click (\fBActionData\fP context)"

.PP
constructor, initialises Action using the ActionData passed in as a param 
.PP
\fBParameters:\fP
.RS 4
\fIcontext\fP an ActionData 
.RE
.PP

.PP
Definition at line 39 of file Click\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.model\&.action\&.elementActions\&.Click\&.execute (int n) throws \fBActionDataException\fP, \fBClickException\fP"

.PP
This performs the click action\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP the index of the element to click on (as taken from the ActionData) 
.RE
.PP
\fBReturns:\fP
.RS 4
String verifying success of click action 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIActionDataException\fP 
.br
\fIActionException\fP 
.RE
.PP

.PP
Definition at line 50 of file Click\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
