.TH "beseenium.view.outputHandlers.requestHandlers.executeHandlers.ActionDataExceptionHandler" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.outputHandlers.requestHandlers.executeHandlers.ActionDataExceptionHandler \- This represents a handler for the case where, an element scoped action has been performed before a findElementsBy\&.\&.\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.view\&.outputHandlers\&.requestHandlers\&.AbstractRequestHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBhandleRequest\fP (\fBAbstractTestRequest\fP request, \fBTest\fP test)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final Logger \fBlogger\fP"
.br
.RI "\fIrefefrence to log4j logger \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This represents a handler for the case where, an element scoped action has been performed before a findElementsBy\&.\&.\&. 

action has loaded a webElement\&. The user is provided with this information\&. 
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 32 of file ActionDataExceptionHandler\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.view\&.outputHandlers\&.requestHandlers\&.executeHandlers\&.ActionDataExceptionHandler\&.handleRequest (\fBAbstractTestRequest\fP request, \fBTest\fP test)"

.PP
Definition at line 42 of file ActionDataExceptionHandler\&.java\&.
.PP
References beseenium\&.view\&.inputHandlers\&.requests\&.AbstractTestRequest\&.executeRequest()\&.
.SH "Member Data Documentation"
.PP 
.SS "final Logger beseenium\&.view\&.outputHandlers\&.requestHandlers\&.executeHandlers\&.ActionDataExceptionHandler\&.logger\fC [static]\fP, \fC [private]\fP"
\fBInitial value:\fP
.PP
.nf
= LogManager\&.getLogger
            ("BeSeenium\&.view\&.outputHandlers\&.requestHandlers\&.executeHandlers\&.ActionExceptionHandler")
.fi
.PP
refefrence to log4j logger 
.PP
Definition at line 35 of file ActionDataExceptionHandler\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
