.TH "beseenium.exceptions.actionDataExceptions.ActionDataException" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.exceptions.actionDataExceptions.ActionDataException \- Exception applicable to ActionData\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.exceptions\&.BeSeeniumException\fP\&.
.PP
Inherited by \fBbeseenium\&.exceptions\&.actionDataExceptions\&.ActionDataFactoryException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActionDataException\fP ()"
.br
.ti -1c
.RI "\fBActionDataException\fP (String message)"
.br
.RI "\fIinstsnciate excecption with message \fP"
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = 5028456643209737119L"
.br
.RI "\fIserialisation needed to avoid warnings \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Exception applicable to ActionData\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 24 of file ActionDataException\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.exceptions\&.actionDataExceptions\&.ActionDataException\&.ActionDataException ()"

.PP
Definition at line 31 of file ActionDataException\&.java\&.
.SS "beseenium\&.exceptions\&.actionDataExceptions\&.ActionDataException\&.ActionDataException (String message)"

.PP
instsnciate excecption with message 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP string to display 
.RE
.PP

.PP
Definition at line 40 of file ActionDataException\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final long beseenium\&.exceptions\&.actionDataExceptions\&.ActionDataException\&.serialVersionUID = 5028456643209737119L\fC [static]\fP, \fC [private]\fP"

.PP
serialisation needed to avoid warnings 
.PP
Definition at line 29 of file ActionDataException\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
