.TH "beseenium.controller.ActionFactory.elementActions" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.controller.ActionFactory.elementActions \- This package contains all the MakeData derived classes for creating element scoped actions for the \fBActionFactory\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMakeClear\fP"
.br
.RI "\fIcreates a new Clear action \fP"
.ti -1c
.RI "class \fBMakeClick\fP"
.br
.RI "\fIcreates a new click action \fP"
.ti -1c
.RI "class \fBMakeGetAttribute\fP"
.br
.RI "\fIcreates a new GetAttribute action \fP"
.ti -1c
.RI "class \fBMakeGetCssValue\fP"
.br
.RI "\fIcreates a new GetCssValue action \fP"
.ti -1c
.RI "class \fBMakeGetLocation\fP"
.br
.RI "\fIcreates a new GetLocation action \fP"
.ti -1c
.RI "class \fBMakeGetSize\fP"
.br
.RI "\fIcreates a new GetSize action \fP"
.ti -1c
.RI "class \fBMakeGetTagName\fP"
.br
.RI "\fIcreates a new GetTagName action \fP"
.ti -1c
.RI "class \fBMakeGetText\fP"
.br
.RI "\fIcreates a new GetText action \fP"
.ti -1c
.RI "class \fBMakeIsDisplayed\fP"
.br
.RI "\fIcreates a new IsDisplayed action \fP"
.ti -1c
.RI "class \fBMakeIsEnabled\fP"
.br
.RI "\fIcreates a new IsEnabled action \fP"
.ti -1c
.RI "class \fBMakeIsSelected\fP"
.br
.RI "\fIcreates a new IsSelected action \fP"
.ti -1c
.RI "class \fBMakeSendKeys\fP"
.br
.RI "\fIcreates a new SendKeys action \fP"
.ti -1c
.RI "class \fBMakeSubmit\fP"
.br
.RI "\fIcreates a new Submit action \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package contains all the MakeData derived classes for creating element scoped actions for the \fBActionFactory\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
