.TH "beseenium.view.outputHandlers.formatters.JsonFormatter" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.outputHandlers.formatters.JsonFormatter \- This class provides methods to transform strings into JSON format\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.view\&.outputHandlers\&.formatters\&.AbstractOutputFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJsonFormatter\fP ()"
.br
.RI "\fIdefault ctor \fP"
.ti -1c
.RI "String \fBfinalForm\fP (String label, String stringToFormat, String delimiter)"
.br
.RI "\fIformat the end JSON object \fP"
.ti -1c
.RI "String \fBasKVsuperSet\fP (String label, String stringToFormat, String delimiter)"
.br
.RI "\fIformat a string as a JSON array \fP"
.ti -1c
.RI "String \fBasKVset\fP (String label, String stringToFormat, String delimiter)"
.br
.RI "\fIformat a string as a JSON object \fP"
.ti -1c
.RI "String \fBasKeyVal\fP (String key, String value, String delimiter)"
.br
.RI "\fIformats a string as a JSON 'key':'value' pair \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class provides methods to transform strings into JSON format\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 24 of file JsonFormatter\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.view\&.outputHandlers\&.formatters\&.JsonFormatter\&.JsonFormatter ()"

.PP
default ctor 
.PP
Definition at line 29 of file JsonFormatter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.view\&.outputHandlers\&.formatters\&.JsonFormatter\&.asKeyVal (String key, String value, String delimiter)"

.PP
formats a string as a JSON 'key':'value' pair 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP a string representing the key 
.br
\fIvalue\fP a string representing the value 
.RE
.PP
\fBReturns:\fP
.RS 4
a string of the form ''key':'value'' 
.RE
.PP

.PP
Implements \fBbeseenium\&.view\&.outputHandlers\&.formatters\&.AbstractOutputFormatter\fP\&.
.PP
Definition at line 75 of file JsonFormatter\&.java\&.
.SS "String beseenium\&.view\&.outputHandlers\&.formatters\&.JsonFormatter\&.asKVset (String label, String stringToFormat, String delimiter)"

.PP
format a string as a JSON object 
.PP
\fBParameters:\fP
.RS 4
\fIstringToFormat\fP string of the form 'V01 V02 \&.\&.\&. V0n' 
.br
\fIlabel\fP string that precedes the format 
.RE
.PP
\fBReturns:\fP
.RS 4
string of the form '{V01, V02 \&.\&.\&. V0n}' 
.RE
.PP

.PP
Implements \fBbeseenium\&.view\&.outputHandlers\&.formatters\&.AbstractOutputFormatter\fP\&.
.PP
Definition at line 63 of file JsonFormatter\&.java\&.
.SS "String beseenium\&.view\&.outputHandlers\&.formatters\&.JsonFormatter\&.asKVsuperSet (String label, String stringToFormat, String delimiter)"

.PP
format a string as a JSON array 
.PP
\fBParameters:\fP
.RS 4
\fIstringToFormat\fP string of the form 'V01 V02 \&.\&.\&. V0n' 
.br
\fIlabel\fP string that precedes the xtringToformat 
.RE
.PP
\fBReturns:\fP
.RS 4
a string of the form '[V01, V02 \&.\&.\&. V03]' 
.RE
.PP

.PP
Implements \fBbeseenium\&.view\&.outputHandlers\&.formatters\&.AbstractOutputFormatter\fP\&.
.PP
Definition at line 51 of file JsonFormatter\&.java\&.
.SS "String beseenium\&.view\&.outputHandlers\&.formatters\&.JsonFormatter\&.finalForm (String label, String stringToFormat, String delimiter)"

.PP
format the end JSON object 
.PP
\fBParameters:\fP
.RS 4
\fIstringToFormat\fP string of the form 'V01 V02 \&.\&.\&. V0n' 
.br
\fIlabel\fP the label to apply to the end object\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
a string of the form '{'label':}' 
.RE
.PP

.PP
Implements \fBbeseenium\&.view\&.outputHandlers\&.formatters\&.AbstractOutputFormatter\fP\&.
.PP
Definition at line 39 of file JsonFormatter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
