.TH "beseenium.view.outputHandlers" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.outputHandlers \- This is the root package for all the classes necessary for handling the output from an AbstractTestRequest and turning it into manipulable text\&.  

.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcompositors\fP"
.br
.RI "\fIThis package holds the compositors which are used by the output handler to compose the result strings into the format requested by the user\&. \fP"
.ti -1c
.RI "package \fBformatters\fP"
.br
.RI "\fIThis package provides objects that modify the text output of the \fBOutputHandler\fP after AbstractTestRequest's have been processed, into a variety of more usable forms: JSON, XML, etc\&. \fP"
.ti -1c
.RI "package \fBrequestHandlers\fP"
.br
.RI "\fIThis is the root package for all request handlers in the \fBAbstractRequestHandler\fP inheritance hierarchy\&. \fP"
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOutputHandler\fP"
.br
.RI "\fIThis takes an array of AbstractTestRequests and uses it to generate output in various forms\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is the root package for all the classes necessary for handling the output from an AbstractTestRequest and turning it into manipulable text\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
