.TH "beseenium.view.outputHandlers.requestHandlers.addActionHandlers.BadlyFormattedActionHandler" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.outputHandlers.requestHandlers.addActionHandlers.BadlyFormattedActionHandler \- This represents a handler for the case where the user has entered a badly formatted value for the addAction parameter, if this is the case the request will throw a TestException, which is caught by this class and notifies the user of their mistake\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.view\&.outputHandlers\&.requestHandlers\&.AbstractRequestHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBhandleRequest\fP (\fBAbstractTestRequest\fP request, \fBTest\fP test)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final Logger \fBlogger\fP"
.br
.RI "\fIrefefrence to log4j logger \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This represents a handler for the case where the user has entered a badly formatted value for the addAction parameter, if this is the case the request will throw a TestException, which is caught by this class and notifies the user of their mistake\&. 

If the exception caught is not a TestException then the request is propogated down the chain\&.
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 34 of file BadlyFormattedActionHandler\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.view\&.outputHandlers\&.requestHandlers\&.addActionHandlers\&.BadlyFormattedActionHandler\&.handleRequest (\fBAbstractTestRequest\fP request, \fBTest\fP test)"

.PP
Definition at line 44 of file BadlyFormattedActionHandler\&.java\&.
.PP
References beseenium\&.view\&.inputHandlers\&.requests\&.AbstractTestRequest\&.executeRequest()\&.
.PP
Referenced by beseenium\&.view\&.outputHandlers\&.requestHandlers\&.addActionHandlers\&.RootAddActionsHandler\&.handleRequest()\&.
.SH "Member Data Documentation"
.PP 
.SS "final Logger beseenium\&.view\&.outputHandlers\&.requestHandlers\&.addActionHandlers\&.BadlyFormattedActionHandler\&.logger\fC [static]\fP, \fC [private]\fP"
\fBInitial value:\fP
.PP
.nf
= LogManager\&.getLogger
            ("BeSeenium\&.view\&.outputHandlers\&.requestHandlers\&.addActionHandlers\&.ActionNumberFormatHandler")
.fi
.PP
refefrence to log4j logger 
.PP
Definition at line 37 of file BadlyFormattedActionHandler\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
