.TH "beseenium.exceptions.actionExceptions.ClickException" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.exceptions.actionExceptions.ClickException \- Copyright(C) 2015 Jan P\&.C\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.exceptions\&.actionExceptions\&.ActionException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClickException\fP ()"
.br
.ti -1c
.RI "\fBClickException\fP (String message)"
.br
.RI "\fIinstsnciate excecption with message \fP"
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = -1616537734173184555L"
.br
.RI "\fISerialisation needed to avoid warnings\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Copyright(C) 2015 Jan P\&.C\&. 

Hanson & BeSeen Marketing Ltd
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program\&. If not, see http://www.gnu.org/licenses/\&. exception to a click action\&.
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 23 of file ClickException\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.exceptions\&.actionExceptions\&.ClickException\&.ClickException ()"

.PP
Definition at line 32 of file ClickException\&.java\&.
.SS "beseenium\&.exceptions\&.actionExceptions\&.ClickException\&.ClickException (String message)"

.PP
instsnciate excecption with message 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP string to display 
.RE
.PP

.PP
Definition at line 41 of file ClickException\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final long beseenium\&.exceptions\&.actionExceptions\&.ClickException\&.serialVersionUID = -1616537734173184555L\fC [static]\fP, \fC [private]\fP"

.PP
Serialisation needed to avoid warnings\&. 
.PP
Definition at line 29 of file ClickException\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
