.TH "beseenium.controller.ActionDataFactory" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.controller.ActionDataFactory \- This package contains all the classes to do with the \fBActionDataFactory\fP functionality\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActionDataFactory\fP"
.br
.RI "\fIThis Class conforms to a 'factory' pattern, it allows the creation of different ActionData instances\&. \fP"
.ti -1c
.RI "interface \fBMakeData\fP"
.br
.RI "\fIinterface which describes a prototype for creating \fBMakeData\fP objects\&. \fP"
.ti -1c
.RI "class \fBMakeFirefoxData\fP"
.br
.RI "\fImake an ActionData containing a firefox Driver \fP"
.ti -1c
.RI "class \fBMakeHtmlUnitDriverData\fP"
.br
.RI "\fImakes an ActionData containing a HtmlUnitDriver \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package contains all the classes to do with the \fBActionDataFactory\fP functionality\&. 

\fBActionDataFactory\fP is a factory method style class, which uses the \fBMakeData\fP inheritance hierarchy to produce its ActionData objects\&. 
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
