.TH "beseenium.model.action.switchActions.SwitchToDefaultContent" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.model.action.switchActions.SwitchToDefaultContent \- represents a \fBSwitchToDefaultContent\fP action which Selects either the first frame on the page, or the main document when a page contains iframes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.model\&.action\&.AbstractAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSwitchToDefaultContent\fP (\fBActionData\fP \fBcontext\fP)"
.br
.RI "\fIconstructor, initialises Action using the ActionData passed in as a param \fP"
.ti -1c
.RI "String \fBexecute\fP (int n)  throws ActionDataException 	"
.br
.RI "\fIExecutes the switch to the currently active element\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
represents a \fBSwitchToDefaultContent\fP action which Selects either the first frame on the page, or the main document when a page contains iframes\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 28 of file SwitchToDefaultContent\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.model\&.action\&.switchActions\&.SwitchToDefaultContent\&.SwitchToDefaultContent (\fBActionData\fP context)"

.PP
constructor, initialises Action using the ActionData passed in as a param 
.PP
\fBParameters:\fP
.RS 4
\fIcontext\fP an ActionData 
.RE
.PP

.PP
Definition at line 34 of file SwitchToDefaultContent\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.model\&.action\&.switchActions\&.SwitchToDefaultContent\&.execute (int n) throws \fBActionDataException\fP"

.PP
Executes the switch to the currently active element\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP meaningless variable 
.RE
.PP
\fBReturns:\fP
.RS 4
String confirming the element that has been switched to 
.RE
.PP

.PP
Definition at line 43 of file SwitchToDefaultContent\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
