.TH "beseenium.view.outputFormatters.AbstractOutputFormatter" 3 "Thu Sep 17 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.outputFormatters.AbstractOutputFormatter \- Interface that all output formatter classes should subscribe to, allowing the servlet to request an appropriate output format specific to a users request\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBbeseenium\&.view\&.outputFormatters\&.BasicFormatter\fP, and \fBbeseenium\&.view\&.outputFormatters\&.JsonFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBasKeyVal\fP (String key, String val)"
.br
.RI "\fIformat the given string as a key value pair specific to the derived type\&. \fP"
.ti -1c
.RI "String \fBasKVset\fP (String label, String stringToFormat)"
.br
.RI "\fIformat the given string as a key value set specific to the derived type\&. \fP"
.ti -1c
.RI "String \fBasKVsuperSet\fP (String label, String stringToFormat)"
.br
.RI "\fIformat the given string as a key value super set specific to the derived type\&. \fP"
.ti -1c
.RI "String \fBfinalForm\fP (String label, String stringToFormat)"
.br
.RI "\fIdo some final formatting on the given string to put it in the final form specific to the derived type\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface that all output formatter classes should subscribe to, allowing the servlet to request an appropriate output format specific to a users request\&. 

Output formatting is divided into 4 generic sections which should be able to apply to all formats that the user could request:
.PP
\fBKeyVal\fP a key value pair, in the case of JSON this would be 'key':'value' for XML it would be <key>value</key> and so on\&.
.PP
\fBKVset\fP this is a set of key value pairs organised in a way that makes sense to the output type: JSON: {'key1':'val1', 'key2':'val2', etc} XML:<setName><key1>value1</key1><key2>value2 </key2></setName> and so on\&.
.PP
\fBKVsuperSet\fP this is a set of key value sets organised in a way that makes sense to the output type
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 39 of file AbstractOutputFormatter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.view\&.outputFormatters\&.AbstractOutputFormatter\&.asKeyVal (String key, String val)"

.PP
format the given string as a key value pair specific to the derived type\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstringToFormat\fP the string to format 
.RE
.PP
\fBReturns:\fP
.RS 4
String formatted as requested 
.RE
.PP

.PP
Implemented in \fBbeseenium\&.view\&.outputFormatters\&.JsonFormatter\fP, and \fBbeseenium\&.view\&.outputFormatters\&.BasicFormatter\fP\&.
.SS "String beseenium\&.view\&.outputFormatters\&.AbstractOutputFormatter\&.asKVset (String label, String stringToFormat)"

.PP
format the given string as a key value set specific to the derived type\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstringToFormat\fP the string to format 
.br
\fIlabel\fP a string to use as a label in the KVSet (optional) 
.RE
.PP
\fBReturns:\fP
.RS 4
String formatted as requested 
.RE
.PP

.PP
Implemented in \fBbeseenium\&.view\&.outputFormatters\&.JsonFormatter\fP, and \fBbeseenium\&.view\&.outputFormatters\&.BasicFormatter\fP\&.
.SS "String beseenium\&.view\&.outputFormatters\&.AbstractOutputFormatter\&.asKVsuperSet (String label, String stringToFormat)"

.PP
format the given string as a key value super set specific to the derived type\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstringToFormat\fP the string to format 
.br
\fIlabel\fP a string to use as a label in the KVsuperSet (optional) 
.RE
.PP
\fBReturns:\fP
.RS 4
String formatted as requested 
.RE
.PP

.PP
Implemented in \fBbeseenium\&.view\&.outputFormatters\&.BasicFormatter\fP, and \fBbeseenium\&.view\&.outputFormatters\&.JsonFormatter\fP\&.
.SS "String beseenium\&.view\&.outputFormatters\&.AbstractOutputFormatter\&.finalForm (String label, String stringToFormat)"

.PP
do some final formatting on the given string to put it in the final form specific to the derived type\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstringToFormat\fP the string to format 
.br
\fIlabel\fP a string to use as a label in the final form (optional) 
.RE
.PP
\fBReturns:\fP
.RS 4
String formatted as requested 
.RE
.PP

.PP
Implemented in \fBbeseenium\&.view\&.outputFormatters\&.BasicFormatter\fP, and \fBbeseenium\&.view\&.outputFormatters\&.JsonFormatter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
