.TH "beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.BadlyFormedCapsStringHandler" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.BadlyFormedCapsStringHandler \- This represents a handler for the case in which the user has made some elementary mistake in the length of the capabilities substring, either too few or too many parameters or the correct spacer has not been used etc\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.view\&.outputHandlers\&.requestHandlers\&.AbstractRequestHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBhandleRequest\fP (\fBAbstractTestRequest\fP request, \fBTest\fP test)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final Logger \fBlogger\fP"
.br
.RI "\fIrefefrence to log4j logger \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This represents a handler for the case in which the user has made some elementary mistake in the length of the capabilities substring, either too few or too many parameters or the correct spacer has not been used etc\&. 

In this case the request will throw a TestException which will be caught here, and the user will be provided with appropriate information\&. 
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 33 of file BadlyFormedCapsStringHandler\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.view\&.outputHandlers\&.requestHandlers\&.capabilitiesHandlers\&.BadlyFormedCapsStringHandler\&.handleRequest (\fBAbstractTestRequest\fP request, \fBTest\fP test)"

.PP
Definition at line 43 of file BadlyFormedCapsStringHandler\&.java\&.
.PP
References beseenium\&.view\&.inputHandlers\&.requests\&.AbstractTestRequest\&.executeRequest()\&.
.SH "Member Data Documentation"
.PP 
.SS "final Logger beseenium\&.view\&.outputHandlers\&.requestHandlers\&.capabilitiesHandlers\&.BadlyFormedCapsStringHandler\&.logger\fC [static]\fP, \fC [private]\fP"
\fBInitial value:\fP
.PP
.nf
= LogManager\&.getLogger
            ("BeSeenium\&.view\&.outputHandlers\&.requestHandlers\&.capabilitiesHandlers\&.BadlyFormedStringHandler")
.fi
.PP
refefrence to log4j logger 
.PP
Definition at line 36 of file BadlyFormedCapsStringHandler\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
