.TH "beseenium" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium \- This is the root package for the BeSeenium project, it contains the entry point into the application\&.  

.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcontroller\fP"
.br
.RI "\fIThe root package for the controller module of the BeSeenium project\&. \fP"
.ti -1c
.RI "package \fBexceptions\fP"
.br
.RI "\fIThis package is the root package for all custom BeSeenium exceptions, it contains the root of the \fBBeSeeniumException\fP inheritance hierarchy, all derived exceptions are located in sub-packages\&. \fP"
.ti -1c
.RI "package \fBhelpers\fP"
.br
.RI "\fIThis package contains generic helper classes\&. \fP"
.ti -1c
.RI "package \fBmodel\fP"
.br
.RI "\fIThis is the root package for the Model module of the BeSeenium application, it contains all the classes related to the data model\&. \fP"
.ti -1c
.RI "package \fBview\fP"
.br
.RI "\fIThis is the root package for the View module of the application\&. \fP"
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMain\fP"
.br
.RI "\fIThis is the main entry point for the program, initial setup and configuration done here\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is the root package for the BeSeenium project, it contains the entry point into the application\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
