.TH "beseenium.exceptions.testExceptions" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.exceptions.testExceptions \- This package contains exceptions relevant to Test objects\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestException\fP"
.br
.RI "\fIException that apply to Test's\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package contains exceptions relevant to Test objects\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
