.TH "beseenium.model.helpers" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.model.helpers \- This package contains helper classes that do not have any particular place in the design but are none the less neccessary for the operation of the application\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFormatOutput\fP"
.br
.RI "\fIThis helper class provides methods to format the output of individual actions\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package contains helper classes that do not have any particular place in the design but are none the less neccessary for the operation of the application\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
