.TH "beseenium.controller.ActionDataFactory.MakeHtmlUnitDriverData" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.controller.ActionDataFactory.MakeHtmlUnitDriverData \- makes an ActionData containing a HtmlUnitDriver  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.controller\&.ActionDataFactory\&.MakeData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMakeHtmlUnitDriverData\fP ()"
.br
.RI "\fIdefault constructor \fP"
.ti -1c
.RI "\fBActionData\fP \fBmakeActionData\fP ()"
.br
.RI "\fIthe factory method that returns the ActionData specific to the derived type of MakeActionData\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
makes an ActionData containing a HtmlUnitDriver 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 26 of file MakeHtmlUnitDriverData\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.controller\&.ActionDataFactory\&.MakeHtmlUnitDriverData\&.MakeHtmlUnitDriverData ()"

.PP
default constructor 
.PP
Definition at line 31 of file MakeHtmlUnitDriverData\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBActionData\fP beseenium\&.controller\&.ActionDataFactory\&.MakeHtmlUnitDriverData\&.makeActionData ()"

.PP
the factory method that returns the ActionData specific to the derived type of MakeActionData\&. 
.PP
\fBReturns:\fP
.RS 4
ActionData appropriate to this type\&. 
.RE
.PP

.PP
Implements \fBbeseenium\&.controller\&.ActionDataFactory\&.MakeData\fP\&.
.PP
Definition at line 38 of file MakeHtmlUnitDriverData\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
