.TH "beseenium.view.helpers.JsonFormatter" 3 "Thu Sep 10 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.helpers.JsonFormatter \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBasArray\fP (String stringToFormat)"
.br
.ti -1c
.RI "String \fBasObject\fP (String stringToFormat)"
.br
.ti -1c
.RI "String \fBasKeyVal\fP (String key, String value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class provides methods to transform strings into JSON format\&. 
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 23 of file JsonFormatter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.view\&.helpers\&.JsonFormatter\&.asArray (String stringToFormat)"
format a string as a JSON array 
.PP
\fBParameters:\fP
.RS 4
\fIstringToFormat\fP string of the form 'V01 V02 \&.\&.\&. V0n' 
.RE
.PP
\fBReturns:\fP
.RS 4
a string of the form '[V01, V02 \&.\&.\&. V03]' 
.RE
.PP

.PP
Definition at line 30 of file JsonFormatter\&.java\&.
.SS "String beseenium\&.view\&.helpers\&.JsonFormatter\&.asKeyVal (String key, String value)"
formats a string as a JSON 'key':'value' pair 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP a string representing the key 
.br
\fIvalue\fP a string representing the value 
.RE
.PP
\fBReturns:\fP
.RS 4
a string of the form ''key':'value'' 
.RE
.PP

.PP
Definition at line 52 of file JsonFormatter\&.java\&.
.SS "String beseenium\&.view\&.helpers\&.JsonFormatter\&.asObject (String stringToFormat)"
format a string as a JSON object 
.PP
\fBParameters:\fP
.RS 4
\fIstringToFormat\fP string of the form 'V01 V02 \&.\&.\&. V0n' 
.RE
.PP
\fBReturns:\fP
.RS 4
string of the form '{V01, V02 \&.\&.\&. V0n}' 
.RE
.PP

.PP
Definition at line 41 of file JsonFormatter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
