.TH "beseenium.view.helpers" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.helpers \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEmergencyShutdown\fP"
.br
.RI "\fIthis is an object wrapper for the emergency shutdown method of the Test class passed in as a parameter\&. \fP"
.ti -1c
.RI "class \fBStringSplit\fP"
.br
.RI "\fIhelper class that splits a string into an appropriate 2d array of strings\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
