.TH "beseenium.model.action.elementActions.GetTagName" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.model.action.elementActions.GetTagName \- This is a \fBGetTagName\fP Action, it retrieves the tag name of the web element selected\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.model\&.action\&.AbstractAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetTagName\fP (\fBActionData\fP \fBcontext\fP)"
.br
.RI "\fIconstructor, initialises Action using the ActionData passed in as a param \fP"
.ti -1c
.RI "String \fBexecute\fP (int n)  throws ActionDataException, ActionException  	"
.br
.RI "\fIThis performs a \fBGetTagName\fP action\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is a \fBGetTagName\fP Action, it retrieves the tag name of the web element selected\&. 


.PP
\fBAuthor:\fP
.RS 4
JPC Hanson 
.RE
.PP

.PP
Definition at line 31 of file GetTagName\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.model\&.action\&.elementActions\&.GetTagName\&.GetTagName (\fBActionData\fP context)"

.PP
constructor, initialises Action using the ActionData passed in as a param 
.PP
\fBParameters:\fP
.RS 4
\fIcontext\fP an ActionData 
.RE
.PP

.PP
Definition at line 37 of file GetTagName\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.model\&.action\&.elementActions\&.GetTagName\&.execute (int n) throws \fBActionDataException\fP, \fBActionException\fP"

.PP
This performs a \fBGetTagName\fP action\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP the index of the element to get the tag name of (as taken from the ActionData) 
.RE
.PP
\fBReturns:\fP
.RS 4
String containing the tag name of the WebElement[n] contained in the ActionData\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIActionDataException\fP 
.br
\fIActionException\fP 
.RE
.PP

.PP
Definition at line 48 of file GetTagName\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
