.TH "beseenium.view.outputFormatters.ExecuteCompositor" 3 "Thu Sep 17 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.outputFormatters.ExecuteCompositor \- Copyright(C) 2015 Jan P\&.C\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.view\&.outputFormatters\&.AbstractCompositor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExecuteCompositor\fP (\fBAbstractOutputFormatter\fP format)"
.br
.RI "\fIconstructor, calls super constructor passing an \fBAbstractOutputFormatter\fP as an argument\&. \fP"
.ti -1c
.RI "String \fBcomposite\fP (String compositorString, String stringToComposite)"
.br
.RI "\fIThis method provides functionality to composite the string into the format specified by the user on creation of this object\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Copyright(C) 2015 Jan P\&.C\&. 

Hanson & BeSeen Marketing Ltd
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program\&. If not, see http://www.gnu.org/licenses/\&.
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 23 of file ExecuteCompositor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.view\&.outputFormatters\&.ExecuteCompositor\&.ExecuteCompositor (\fBAbstractOutputFormatter\fP format)"

.PP
constructor, calls super constructor passing an \fBAbstractOutputFormatter\fP as an argument\&. 
.PP
\fBParameters:\fP
.RS 4
\fIformat\fP an \fBAbstractOutputFormatter\fP\&. 
.RE
.PP

.PP
Definition at line 30 of file ExecuteCompositor\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.view\&.outputFormatters\&.ExecuteCompositor\&.composite (String compositorString, String stringToComposite)"

.PP
This method provides functionality to composite the string into the format specified by the user on creation of this object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcompositorString\fP representation of the type of string that this is i\&.e\&. execute, addAction, capabilities or browser\&. 
.br
\fIstringToComposite\fP the string that requires formatting 
.RE
.PP
\fBReturns:\fP
.RS 4
String the formatted string\&. 
.RE
.PP

.PP
Definition at line 42 of file ExecuteCompositor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
