.TH "beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.RootCapabilitiesHandler" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.outputHandlers.requestHandlers.capabilitiesHandlers.RootCapabilitiesHandler \- This class is the root of the capabilities chain of responsibility, it takes care of defining the chain and, assuming the request fails, passing it to the first handler in the chain\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.view\&.outputHandlers\&.requestHandlers\&.AbstractRequestHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRootCapabilitiesHandler\fP ()"
.br
.RI "\fIdefault ctor \fP"
.ti -1c
.RI "String \fBhandleRequest\fP (\fBAbstractTestRequest\fP request, \fBTest\fP test)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This class is the root of the capabilities chain of responsibility, it takes care of defining the chain and, assuming the request fails, passing it to the first handler in the chain\&. 

The request then propagates down the chain until it gets handled, or in the worst case scenario, drops off the end of the chain without being handled\&.
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 30 of file RootCapabilitiesHandler\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.view\&.outputHandlers\&.requestHandlers\&.capabilitiesHandlers\&.RootCapabilitiesHandler\&.RootCapabilitiesHandler ()"

.PP
default ctor 
.PP
Definition at line 35 of file RootCapabilitiesHandler\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.view\&.outputHandlers\&.requestHandlers\&.capabilitiesHandlers\&.RootCapabilitiesHandler\&.handleRequest (\fBAbstractTestRequest\fP request, \fBTest\fP test)"

.PP
Definition at line 45 of file RootCapabilitiesHandler\&.java\&.
.PP
References beseenium\&.view\&.inputHandlers\&.requests\&.AbstractTestRequest\&.executeRequest(), beseenium\&.view\&.outputHandlers\&.requestHandlers\&.capabilitiesHandlers\&.EmptyCapsParamHandler\&.handleRequest(), and beseenium\&.view\&.outputHandlers\&.requestHandlers\&.AbstractRequestHandler\&.setSuccessor()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
