.TH "beseenium.view.inputHandlers.requests.BrowserRequest" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.view.inputHandlers.requests.BrowserRequest \- This class represents a request for a test to use a particular browser type\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbeseenium\&.view\&.inputHandlers\&.requests\&.AbstractTestRequest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBrowserRequest\fP (String \fBrequestData\fP)"
.br
.RI "\fIcall super constructor passing in the appropriate request data\&. \fP"
.ti -1c
.RI "String \fBexecuteRequest\fP (\fBTest\fP test)  throws ActionDataException, NullPointerException 	"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This class represents a request for a test to use a particular browser type\&. 


.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.PP
Definition at line 25 of file BrowserRequest\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beseenium\&.view\&.inputHandlers\&.requests\&.BrowserRequest\&.BrowserRequest (String requestData)"

.PP
call super constructor passing in the appropriate request data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrequestData\fP String representation of the WebDriver to use ('firefox'/'noWindows'/'remote'\&.\&.\&.etc) 
.RE
.PP

.PP
Definition at line 32 of file BrowserRequest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String beseenium\&.view\&.inputHandlers\&.requests\&.BrowserRequest\&.executeRequest (\fBTest\fP test) throws \fBActionDataException\fP, NullPointerException"

.PP
Definition at line 44 of file BrowserRequest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
