.TH "beseenium.model.action.findElementsBy" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beseenium.model.action.findElementsBy \- This package contains FindElementsBy\&.\&.\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFindElementsByClass\fP"
.br
.RI "\fIThis class represents a FindElementByClass Action, it takes an ActionData object in initialiseation which should contain an appropriate searchParam and returnParam\&. \fP"
.ti -1c
.RI "class \fBFindElementsByCss\fP"
.br
.RI "\fIthis is a FindElementByCss Action, it takes an ActionData object in initialiseation which should contain an appropriate searchParam and returnParam\&. \fP"
.ti -1c
.RI "class \fBFindElementsById\fP"
.br
.RI "\fIThis class represents a FindElementById Action, it takes an ActionData object in initialiseation which should contain an appropriate searchParam and returnParam\&. \fP"
.ti -1c
.RI "class \fBFindElementsByLinkTxt\fP"
.br
.RI "\fIthis is a find element by link text action, it searches for an element using a string containing 'link text' i\&.e\&. \fP"
.ti -1c
.RI "class \fBFindElementsByName\fP"
.br
.RI "\fIthis is a find elements by name action, it attempts to find an element using a name provided i\&.e\&. \fP"
.ti -1c
.RI "class \fBFindElementsByPartialLinkTxt\fP"
.br
.RI "\fIthis is a find element by partial link text action, it searches for an element using a string containing 'partial link text' i\&.e\&. \fP"
.ti -1c
.RI "class \fBFindElementsByTagName\fP"
.br
.RI "\fIthis is a find elements by tag name, it finds an element using a provided tag name string\&. \fP"
.ti -1c
.RI "class \fBFindElementsByXpath\fP"
.br
.RI "\fIis a Find element by Xpath action, it provides a method to find an element using an xpath string\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This package contains FindElementsBy\&.\&.\&. 

actions, these can take a variety of inputs, depending on the particular class: CSS selector, Xpath query, id, class, etc and return a webElement that matches the criterion specified\&.
.PP
All classes in this package are concrete command objects and are part of the \fBAbstractAction\fP inheritance hierarchy\&.
.PP
\fBAuthor:\fP
.RS 4
Jan P\&.C\&. Hanson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
