.TH "BrowserCompositor.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrowserCompositor.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.view\&.outputHandlers\&.compositors\&.BrowserCompositor\fP"
.br
.RI "\fICopyright(C) 2015 Jan P\&.C\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.view\&.outputHandlers\&.compositors\fP"
.br
.RI "\fIThis package holds the compositors which are used by the output handler to compose the result strings into the format requested by the user\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
