.TH "CapsActionDataHandler.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CapsActionDataHandler.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.view\&.outputHandlers\&.requestHandlers\&.capabilitiesHandlers\&.CapsActionDataHandler\fP"
.br
.RI "\fIThis represents a handler for the case in which the ActionData object has not been correctly used, this is more than likely a backend issue and is something that only a developer can deal with\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.view\&.outputHandlers\&.requestHandlers\&.capabilitiesHandlers\fP"
.br
.RI "\fIThis package contains all classes relevant to the chain of responsibility that processes the 'capabilities' url query string\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
