.TH "Clear.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clear.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.model\&.action\&.elementActions\&.Clear\fP"
.br
.RI "\fIThis represents a clear action, it will have no effect unless the element that this action is performed on is a text entry element, i\&.e\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.model\&.action\&.elementActions\fP"
.br
.RI "\fIThis package contains all the concrete command classes relevant to element-scoped actions, i\&.e\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
