.TH "ClickException.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClickException.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.exceptions\&.actionExceptions\&.ClickException\fP"
.br
.RI "\fICopyright(C) 2015 Jan P\&.C\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.exceptions\&.actionExceptions\fP"
.br
.RI "\fIThis package contains all exceptions relating to AbstractAction objects, their creation and their use\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
