.TH "FindElementsByLinkTxt.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FindElementsByLinkTxt.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.model\&.action\&.findElementsBy\&.FindElementsByLinkTxt\fP"
.br
.RI "\fIthis is a find element by link text action, it searches for an element using a string containing 'link text' i\&.e\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.model\&.action\&.findElementsBy\fP"
.br
.RI "\fIThis package contains FindElementsBy\&.\&.\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
