.TH "FindElementsByTagName.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FindElementsByTagName.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.model\&.action\&.findElementsBy\&.FindElementsByTagName\fP"
.br
.RI "\fIthis is a find elements by tag name, it finds an element using a provided tag name string\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.model\&.action\&.findElementsBy\fP"
.br
.RI "\fIThis package contains FindElementsBy\&.\&.\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
