.TH "GetTagName.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetTagName.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.model\&.action\&.elementActions\&.GetTagName\fP"
.br
.RI "\fIThis is a \fBGetTagName\fP Action, it retrieves the tag name of the web element selected\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.model\&.action\&.elementActions\fP"
.br
.RI "\fIThis package contains all the concrete command classes relevant to element-scoped actions, i\&.e\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
