.TH "JsonFormatter.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsonFormatter.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.view\&.outputHandlers\&.formatters\&.JsonFormatter\fP"
.br
.RI "\fIThis class provides methods to transform strings into JSON format\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.view\&.outputHandlers\&.formatters\fP"
.br
.RI "\fIThis package provides objects that modify the text output of the \fBOutputHandler\fP after AbstractTestRequest's have been processed, into a variety of more usable forms: JSON, XML, etc\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
