.TH "Main.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.Main\fP"
.br
.RI "\fIThis is the main entry point for the program, initial setup and configuration done here\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\fP"
.br
.RI "\fIThis is the root package for the BeSeenium project, it contains the entry point into the application\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
