.TH "MakeFirefoxData.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeFirefoxData.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.controller\&.ActionDataFactory\&.MakeFirefoxData\fP"
.br
.RI "\fImake an ActionData containing a firefox Driver \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.controller\&.ActionDataFactory\fP"
.br
.RI "\fIThis package contains all the classes to do with the \fBActionDataFactory\fP functionality\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
