.TH "MakeNavigateBack.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeNavigateBack.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.controller\&.ActionFactory\&.navigateActions\&.MakeNavigateBack\fP"
.br
.RI "\fIcreates new NavigateBack action \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.controller\&.ActionFactory\&.navigateActions\fP"
.br
.RI "\fIThis package contains all the MakeData derived classes needed for the \fBActionFactory\fP to create navigation type action objects\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
