.TH "MakeGetTagName.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeGetTagName.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.controller\&.ActionFactory\&.elementActions\&.MakeGetTagName\fP"
.br
.RI "\fIcreates a new GetTagName action \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.controller\&.ActionFactory\&.elementActions\fP"
.br
.RI "\fIThis package contains all the MakeData derived classes for creating element scoped actions for the \fBActionFactory\fP\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
