.TH "NavigateForward.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NavigateForward.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.model\&.action\&.navigateActions\&.NavigateForward\fP"
.br
.RI "\fIThis is a navigate forward action, it attempts to use the back/foward history to navigate forward a specified number of times\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.model\&.action\&.navigateActions\fP"
.br
.RI "\fIThis package contains all actions related to browser based navigation, and are analagoug to many of the buttons found at the top of a browser: back, forward, refresh etc\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
