.TH "PageClose.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PageClose.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.model\&.action\&.pageActions\&.PageClose\fP"
.br
.RI "\fIThis is a Close Action, it essentially closes the current tab, if it is the last or only tab open it also closes the browser\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.model\&.action\&.pageActions\fP"
.br
.RI "\fIThis package contains the majority of page-scoped actions, that is actions which apply to a web page as a whole, things like: get a pages URL, or retrieve the title of the page\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
