.TH "ResetActionData.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResetActionData.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.model\&.action\&.ResetActionData\fP"
.br
.RI "\fIthis resets various attributes of the ActionData \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.model\&.action\fP"
.br
.RI "\fIThis package is the root of all \fBAbstractAction\fP objects, while this package contains only the \fBAbstractAction\fP class its derived classes are located in sub-packages beneath this one\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
