.TH "RootExecuteHandler.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RootExecuteHandler.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.view\&.outputHandlers\&.requestHandlers\&.executeHandlers\&.RootExecuteHandler\fP"
.br
.RI "\fIThis class is the root of the addAction chain of responsibility, it takes care of defining the chain and, assuming the request fails, passing it to the first handler in the chain\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.view\&.outputHandlers\&.requestHandlers\&.executeHandlers\fP"
.br
.RI "\fIThis package is responsible for the chain of responsibility that executes a Test after all inputs have been checked for errors\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
