.TH "StringSplit.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringSplit.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.view\&.helpers\&.StringSplit\fP"
.br
.RI "\fIhelper class that splits a string into an appropriate 2d array of strings\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.view\&.helpers\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
