.TH "SwitchToActiveElement.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SwitchToActiveElement.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbeseenium\&.model\&.action\&.switchActions\&.SwitchToActiveElement\fP"
.br
.RI "\fIthis is a \fBSwitchToActiveElement\fP, it Switches to the element that currently has focus within the document currently 'switched to', or the body element if this cannot be detected\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.model\&.action\&.switchActions\fP"
.br
.RI "\fIThis package contains elements which relate to switching actions, for instance, switch to a different browser window, tab, or popup etc\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
