.TH "test" 3 "Sat Sep 12 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test \- my first page 
this is a test
.PP
title
.PP
.IP "\(bu" 2
\fBmy sub page\fP
.IP "\(bu" 2
\fBmy second sub page\fP
.PP
.SH "my first section"
.PP
sadfdsfdsfa sdfasdfsafds safdsdafasdf
.SS "my second sub section"
sadfsdaf sdfsdf sadfdsfs
.SS "asdfdsafdsafsa"
sdfsdafsdafa
.SH "my first section"
.PP
sadfdsfdsfa sdfasdfsafds safdsdafasdf
.SS "my second sub section"
sadfsdaf sdfsdf sadfdsfs
.SS "asdfdsafdsafsa"
sdfsdafsdafa 
