.TH "todo" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBClass \fBbeseenium\&.view\&.outputHandlers\&.formatters\&.BasicFormatter\fP \fP" 1c
implement \fBBasicFormatter\fP properly  
.IP "\fBMember \fBbeseenium\&.view\&.URLHandler\&.handleURL\fP (String capabilities, String browser, String addActions)\fP" 1c
add more browser drivers 
.PP

