.TH "package-info.java" 3 "Thu Sep 17 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
package-info.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.view\&.outputFormatters\fP"
.br
.RI "\fIThis package provides objects that modify the text output of the OutputHandler after AbstractTestRequest's have been processed, into a variety of more usable forms: JSON, XML, etc\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
