.TH "package-info.java" 3 "Fri Sep 25 2015" "Version 1.0.0-Alpha" "BeSeenium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
package-info.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBbeseenium\&.view\&.outputHandlers\fP"
.br
.RI "\fIThis is the root package for all the classes necessary for handling the output from an AbstractTestRequest and turning it into manipulable text\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BeSeenium from the source code\&.
